<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imp/business/imp_common.proto

namespace Volc\Service\Imp\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Imp.Models.Business.Input</code>
 */
class Input extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.InputPath InputPath = 1;</code>
     */
    protected $InputPath = null;
    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.Clip Clip = 2;</code>
     */
    protected $Clip = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Volc\Service\Imp\Models\Business\InputPath $InputPath
     *     @type \Volc\Service\Imp\Models\Business\Clip $Clip
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Imp\Models\GPBMetadata\ImpCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.InputPath InputPath = 1;</code>
     * @return \Volc\Service\Imp\Models\Business\InputPath|null
     */
    public function getInputPath()
    {
        return $this->InputPath;
    }

    public function hasInputPath()
    {
        return isset($this->InputPath);
    }

    public function clearInputPath()
    {
        unset($this->InputPath);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.InputPath InputPath = 1;</code>
     * @param \Volc\Service\Imp\Models\Business\InputPath $var
     * @return $this
     */
    public function setInputPath($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Imp\Models\Business\InputPath::class);
        $this->InputPath = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.Clip Clip = 2;</code>
     * @return \Volc\Service\Imp\Models\Business\Clip|null
     */
    public function getClip()
    {
        return $this->Clip;
    }

    public function hasClip()
    {
        return isset($this->Clip);
    }

    public function clearClip()
    {
        unset($this->Clip);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.Clip Clip = 2;</code>
     * @param \Volc\Service\Imp\Models\Business\Clip $var
     * @return $this
     */
    public function setClip($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Imp\Models\Business\Clip::class);
        $this->Clip = $var;

        return $this;
    }

}

