<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imp/business/imp_common.proto

namespace Volc\Service\Imp\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Imp.Models.Business.Job</code>
 */
class Job extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.TranscodeVideoJob TranscodeVideo = 1;</code>
     */
    protected $TranscodeVideo = null;
    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.ByteHDJob ByteHD = 2;</code>
     */
    protected $ByteHD = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Volc\Service\Imp\Models\Business\TranscodeVideoJob $TranscodeVideo
     *     @type \Volc\Service\Imp\Models\Business\ByteHDJob $ByteHD
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Imp\Models\GPBMetadata\ImpCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.TranscodeVideoJob TranscodeVideo = 1;</code>
     * @return \Volc\Service\Imp\Models\Business\TranscodeVideoJob|null
     */
    public function getTranscodeVideo()
    {
        return $this->TranscodeVideo;
    }

    public function hasTranscodeVideo()
    {
        return isset($this->TranscodeVideo);
    }

    public function clearTranscodeVideo()
    {
        unset($this->TranscodeVideo);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.TranscodeVideoJob TranscodeVideo = 1;</code>
     * @param \Volc\Service\Imp\Models\Business\TranscodeVideoJob $var
     * @return $this
     */
    public function setTranscodeVideo($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Imp\Models\Business\TranscodeVideoJob::class);
        $this->TranscodeVideo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.ByteHDJob ByteHD = 2;</code>
     * @return \Volc\Service\Imp\Models\Business\ByteHDJob|null
     */
    public function getByteHD()
    {
        return $this->ByteHD;
    }

    public function hasByteHD()
    {
        return isset($this->ByteHD);
    }

    public function clearByteHD()
    {
        unset($this->ByteHD);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.ByteHDJob ByteHD = 2;</code>
     * @param \Volc\Service\Imp\Models\Business\ByteHDJob $var
     * @return $this
     */
    public function setByteHD($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Imp\Models\Business\ByteHDJob::class);
        $this->ByteHD = $var;

        return $this;
    }

}

