<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imp/business/imp_common.proto

namespace Volc\Service\Imp\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Imp.Models.Business.SmartEraseOverrideParams</code>
 */
class SmartEraseOverrideParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string ActivityId = 1;</code>
     */
    private $ActivityId;
    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.Watermark Watermark = 2;</code>
     */
    protected $Watermark = null;
    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.OCR OCR = 3;</code>
     */
    protected $OCR = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $ActivityId
     *     @type \Volc\Service\Imp\Models\Business\Watermark $Watermark
     *     @type \Volc\Service\Imp\Models\Business\OCR $OCR
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Imp\Models\GPBMetadata\ImpCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string ActivityId = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActivityId()
    {
        return $this->ActivityId;
    }

    /**
     * Generated from protobuf field <code>repeated string ActivityId = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActivityId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ActivityId = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.Watermark Watermark = 2;</code>
     * @return \Volc\Service\Imp\Models\Business\Watermark
     */
    public function getWatermark()
    {
        return $this->Watermark;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.Watermark Watermark = 2;</code>
     * @param \Volc\Service\Imp\Models\Business\Watermark $var
     * @return $this
     */
    public function setWatermark($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Imp\Models\Business\Watermark::class);
        $this->Watermark = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.OCR OCR = 3;</code>
     * @return \Volc\Service\Imp\Models\Business\OCR
     */
    public function getOCR()
    {
        return $this->OCR;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.OCR OCR = 3;</code>
     * @param \Volc\Service\Imp\Models\Business\OCR $var
     * @return $this
     */
    public function setOCR($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Imp\Models\Business\OCR::class);
        $this->OCR = $var;

        return $this;
    }

}

