<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imp/business/imp_common.proto

namespace Volc\Service\Imp\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Imp.Models.Business.SmartEmoticonOverrideParams</code>
 */
class SmartEmoticonOverrideParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string ActivityId = 1;</code>
     */
    private $ActivityId;
    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.InputPath DrivenVideo = 2;</code>
     */
    protected $DrivenVideo = null;
    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.InputPath DrivenAudio = 3;</code>
     */
    protected $DrivenAudio = null;
    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.DrivenTextParams DrivenTextParams = 4;</code>
     */
    protected $DrivenTextParams = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $ActivityId
     *     @type \Volc\Service\Imp\Models\Business\InputPath $DrivenVideo
     *     @type \Volc\Service\Imp\Models\Business\InputPath $DrivenAudio
     *     @type \Volc\Service\Imp\Models\Business\DrivenTextParams $DrivenTextParams
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Imp\Models\GPBMetadata\ImpCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string ActivityId = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActivityId()
    {
        return $this->ActivityId;
    }

    /**
     * Generated from protobuf field <code>repeated string ActivityId = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActivityId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ActivityId = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.InputPath DrivenVideo = 2;</code>
     * @return \Volc\Service\Imp\Models\Business\InputPath|null
     */
    public function getDrivenVideo()
    {
        return $this->DrivenVideo;
    }

    public function hasDrivenVideo()
    {
        return isset($this->DrivenVideo);
    }

    public function clearDrivenVideo()
    {
        unset($this->DrivenVideo);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.InputPath DrivenVideo = 2;</code>
     * @param \Volc\Service\Imp\Models\Business\InputPath $var
     * @return $this
     */
    public function setDrivenVideo($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Imp\Models\Business\InputPath::class);
        $this->DrivenVideo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.InputPath DrivenAudio = 3;</code>
     * @return \Volc\Service\Imp\Models\Business\InputPath|null
     */
    public function getDrivenAudio()
    {
        return $this->DrivenAudio;
    }

    public function hasDrivenAudio()
    {
        return isset($this->DrivenAudio);
    }

    public function clearDrivenAudio()
    {
        unset($this->DrivenAudio);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.InputPath DrivenAudio = 3;</code>
     * @param \Volc\Service\Imp\Models\Business\InputPath $var
     * @return $this
     */
    public function setDrivenAudio($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Imp\Models\Business\InputPath::class);
        $this->DrivenAudio = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.DrivenTextParams DrivenTextParams = 4;</code>
     * @return \Volc\Service\Imp\Models\Business\DrivenTextParams|null
     */
    public function getDrivenTextParams()
    {
        return $this->DrivenTextParams;
    }

    public function hasDrivenTextParams()
    {
        return isset($this->DrivenTextParams);
    }

    public function clearDrivenTextParams()
    {
        unset($this->DrivenTextParams);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Imp.Models.Business.DrivenTextParams DrivenTextParams = 4;</code>
     * @param \Volc\Service\Imp\Models\Business\DrivenTextParams $var
     * @return $this
     */
    public function setDrivenTextParams($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Imp\Models\Business\DrivenTextParams::class);
        $this->DrivenTextParams = $var;

        return $this;
    }

}

