<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imp/business/imp_common.proto

namespace Volc\Service\Imp\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Imp.Models.Business.TTSParams</code>
 */
class TTSParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string VoiceType = 1;</code>
     */
    protected $VoiceType = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $VoiceType
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Imp\Models\GPBMetadata\ImpCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string VoiceType = 1;</code>
     * @return string
     */
    public function getVoiceType()
    {
        return $this->VoiceType;
    }

    /**
     * Generated from protobuf field <code>string VoiceType = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVoiceType($var)
    {
        GPBUtil::checkString($var, True);
        $this->VoiceType = $var;

        return $this;
    }

}

