<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_edit.proto

namespace Volc\Service\Vod\Models\GPBMetadata;

class VodEdit
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ê
&volcengine/vod/business/vod_edit.protoVolcengine.Vod.Models.Business"0
SubmitDirectEditTaskAsyncResult
ReqId (	"\'
GetDirectEditProgress
Result ("ó
GetDirectEditResult
ReqId (	
	EditParam (
Priority (
CallbackUri (	
CallbackArgs (	
Status (	
	OutputVid (	B»
)com.volcengine.service.vod.model.businessBVodEditPZAgithub.com/volcengine/volc-sdk-golang/service/vod/models/business†ÿ  Volc\\Service\\Vod\\Models\\Business‚#Volc\\Service\\Vod\\Models\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

