<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_workflow.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.AdaptConcat</code>
 */
class AdaptConcat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.AnchorSize AnchorSize = 1;</code>
     */
    protected $AnchorSize = null;
    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.ConcatDefinition Concats = 2;</code>
     */
    private $Concats;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Volc\Service\Vod\Models\Business\AnchorSize $AnchorSize
     *     @type \Volc\Service\Vod\Models\Business\ConcatDefinition[]|\Google\Protobuf\Internal\RepeatedField $Concats
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodWorkflow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.AnchorSize AnchorSize = 1;</code>
     * @return \Volc\Service\Vod\Models\Business\AnchorSize|null
     */
    public function getAnchorSize()
    {
        return $this->AnchorSize;
    }

    public function hasAnchorSize()
    {
        return isset($this->AnchorSize);
    }

    public function clearAnchorSize()
    {
        unset($this->AnchorSize);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.AnchorSize AnchorSize = 1;</code>
     * @param \Volc\Service\Vod\Models\Business\AnchorSize $var
     * @return $this
     */
    public function setAnchorSize($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\AnchorSize::class);
        $this->AnchorSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.ConcatDefinition Concats = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConcats()
    {
        return $this->Concats;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.ConcatDefinition Concats = 2;</code>
     * @param \Volc\Service\Vod\Models\Business\ConcatDefinition[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConcats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Service\Vod\Models\Business\ConcatDefinition::class);
        $this->Concats = $arr;

        return $this;
    }

}

