<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_edit.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.AsyncVCreativeTaskResult</code>
 */
class AsyncVCreativeTaskResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string VCreativeId = 1;</code>
     */
    protected $VCreativeId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $VCreativeId
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodEdit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string VCreativeId = 1;</code>
     * @return string
     */
    public function getVCreativeId()
    {
        return $this->VCreativeId;
    }

    /**
     * Generated from protobuf field <code>string VCreativeId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVCreativeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->VCreativeId = $var;

        return $this;
    }

}

