<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_media.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.AuditResult</code>
 */
class AuditResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Status = 1;</code>
     */
    protected $Status = '';
    /**
     * Generated from protobuf field <code>string Reason = 2;</code>
     */
    protected $Reason = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Status
     *     @type string $Reason
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodMedia::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Status = 1;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * Generated from protobuf field <code>string Status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->Status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Reason = 2;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->Reason;
    }

    /**
     * Generated from protobuf field <code>string Reason = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->Reason = $var;

        return $this;
    }

}

