<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_workflow.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.Audio</code>
 */
class Audio extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Codec = 1;</code>
     */
    protected $Codec = '';
    /**
     * Generated from protobuf field <code>int32 SampleRate = 2;</code>
     */
    protected $SampleRate = 0;
    /**
     * Generated from protobuf field <code>string RateControlMode = 3;</code>
     */
    protected $RateControlMode = '';
    /**
     * Generated from protobuf field <code>int32 Bitrate = 4;</code>
     */
    protected $Bitrate = 0;
    /**
     * Generated from protobuf field <code>int32 MinRate = 5;</code>
     */
    protected $MinRate = 0;
    /**
     * Generated from protobuf field <code>int32 MaxRate = 6;</code>
     */
    protected $MaxRate = 0;
    /**
     * Generated from protobuf field <code>int32 Channels = 7;</code>
     */
    protected $Channels = 0;
    /**
     * Generated from protobuf field <code>string Profile = 8;</code>
     */
    protected $Profile = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Codec
     *     @type int $SampleRate
     *     @type string $RateControlMode
     *     @type int $Bitrate
     *     @type int $MinRate
     *     @type int $MaxRate
     *     @type int $Channels
     *     @type string $Profile
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodWorkflow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Codec = 1;</code>
     * @return string
     */
    public function getCodec()
    {
        return $this->Codec;
    }

    /**
     * Generated from protobuf field <code>string Codec = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCodec($var)
    {
        GPBUtil::checkString($var, True);
        $this->Codec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 SampleRate = 2;</code>
     * @return int
     */
    public function getSampleRate()
    {
        return $this->SampleRate;
    }

    /**
     * Generated from protobuf field <code>int32 SampleRate = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSampleRate($var)
    {
        GPBUtil::checkInt32($var);
        $this->SampleRate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string RateControlMode = 3;</code>
     * @return string
     */
    public function getRateControlMode()
    {
        return $this->RateControlMode;
    }

    /**
     * Generated from protobuf field <code>string RateControlMode = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRateControlMode($var)
    {
        GPBUtil::checkString($var, True);
        $this->RateControlMode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Bitrate = 4;</code>
     * @return int
     */
    public function getBitrate()
    {
        return $this->Bitrate;
    }

    /**
     * Generated from protobuf field <code>int32 Bitrate = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setBitrate($var)
    {
        GPBUtil::checkInt32($var);
        $this->Bitrate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 MinRate = 5;</code>
     * @return int
     */
    public function getMinRate()
    {
        return $this->MinRate;
    }

    /**
     * Generated from protobuf field <code>int32 MinRate = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMinRate($var)
    {
        GPBUtil::checkInt32($var);
        $this->MinRate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 MaxRate = 6;</code>
     * @return int
     */
    public function getMaxRate()
    {
        return $this->MaxRate;
    }

    /**
     * Generated from protobuf field <code>int32 MaxRate = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxRate($var)
    {
        GPBUtil::checkInt32($var);
        $this->MaxRate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Channels = 7;</code>
     * @return int
     */
    public function getChannels()
    {
        return $this->Channels;
    }

    /**
     * Generated from protobuf field <code>int32 Channels = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setChannels($var)
    {
        GPBUtil::checkInt32($var);
        $this->Channels = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Profile = 8;</code>
     * @return string
     */
    public function getProfile()
    {
        return $this->Profile;
    }

    /**
     * Generated from protobuf field <code>string Profile = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkString($var, True);
        $this->Profile = $var;

        return $this;
    }

}

