<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_common.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.BarrageMaskInfo</code>
 */
class BarrageMaskInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * 弹幕蒙板版本v1,v2...
     *
     * Generated from protobuf field <code>string Version = 1;</code>
     */
    protected $Version = '';
    /**
     * 弹幕蒙板url
     *
     * Generated from protobuf field <code>string BarrageMaskUrl = 2;</code>
     */
    protected $BarrageMaskUrl = '';
    /**
     * 弹幕蒙板文件Id
     *
     * Generated from protobuf field <code>string FileId = 3;</code>
     */
    protected $FileId = '';
    /**
     * 弹幕蒙板文件大小
     *
     * Generated from protobuf field <code>double FileSize = 4;</code>
     */
    protected $FileSize = 0.0;
    /**
     * 弹幕蒙板文件哈希
     *
     * Generated from protobuf field <code>string FileHash = 5;</code>
     */
    protected $FileHash = '';
    /**
     * 弹幕蒙板文件更新日期
     *
     * Generated from protobuf field <code>string UpdatedAt = 6;</code>
     */
    protected $UpdatedAt = '';
    /**
     * 弹幕蒙板文件码率
     *
     * Generated from protobuf field <code>int32 Bitrate = 7;</code>
     */
    protected $Bitrate = 0;
    /**
     * 弹幕蒙板文件头部大小
     *
     * Generated from protobuf field <code>double HeadLen = 8;</code>
     */
    protected $HeadLen = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Version
     *           弹幕蒙板版本v1,v2...
     *     @type string $BarrageMaskUrl
     *           弹幕蒙板url
     *     @type string $FileId
     *           弹幕蒙板文件Id
     *     @type float $FileSize
     *           弹幕蒙板文件大小
     *     @type string $FileHash
     *           弹幕蒙板文件哈希
     *     @type string $UpdatedAt
     *           弹幕蒙板文件更新日期
     *     @type int $Bitrate
     *           弹幕蒙板文件码率
     *     @type float $HeadLen
     *           弹幕蒙板文件头部大小
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodCommon::initOnce();
        parent::__construct($data);
    }

    /**
     * 弹幕蒙板版本v1,v2...
     *
     * Generated from protobuf field <code>string Version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->Version;
    }

    /**
     * 弹幕蒙板版本v1,v2...
     *
     * Generated from protobuf field <code>string Version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->Version = $var;

        return $this;
    }

    /**
     * 弹幕蒙板url
     *
     * Generated from protobuf field <code>string BarrageMaskUrl = 2;</code>
     * @return string
     */
    public function getBarrageMaskUrl()
    {
        return $this->BarrageMaskUrl;
    }

    /**
     * 弹幕蒙板url
     *
     * Generated from protobuf field <code>string BarrageMaskUrl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBarrageMaskUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->BarrageMaskUrl = $var;

        return $this;
    }

    /**
     * 弹幕蒙板文件Id
     *
     * Generated from protobuf field <code>string FileId = 3;</code>
     * @return string
     */
    public function getFileId()
    {
        return $this->FileId;
    }

    /**
     * 弹幕蒙板文件Id
     *
     * Generated from protobuf field <code>string FileId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFileId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FileId = $var;

        return $this;
    }

    /**
     * 弹幕蒙板文件大小
     *
     * Generated from protobuf field <code>double FileSize = 4;</code>
     * @return float
     */
    public function getFileSize()
    {
        return $this->FileSize;
    }

    /**
     * 弹幕蒙板文件大小
     *
     * Generated from protobuf field <code>double FileSize = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setFileSize($var)
    {
        GPBUtil::checkDouble($var);
        $this->FileSize = $var;

        return $this;
    }

    /**
     * 弹幕蒙板文件哈希
     *
     * Generated from protobuf field <code>string FileHash = 5;</code>
     * @return string
     */
    public function getFileHash()
    {
        return $this->FileHash;
    }

    /**
     * 弹幕蒙板文件哈希
     *
     * Generated from protobuf field <code>string FileHash = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFileHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->FileHash = $var;

        return $this;
    }

    /**
     * 弹幕蒙板文件更新日期
     *
     * Generated from protobuf field <code>string UpdatedAt = 6;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->UpdatedAt;
    }

    /**
     * 弹幕蒙板文件更新日期
     *
     * Generated from protobuf field <code>string UpdatedAt = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->UpdatedAt = $var;

        return $this;
    }

    /**
     * 弹幕蒙板文件码率
     *
     * Generated from protobuf field <code>int32 Bitrate = 7;</code>
     * @return int
     */
    public function getBitrate()
    {
        return $this->Bitrate;
    }

    /**
     * 弹幕蒙板文件码率
     *
     * Generated from protobuf field <code>int32 Bitrate = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setBitrate($var)
    {
        GPBUtil::checkInt32($var);
        $this->Bitrate = $var;

        return $this;
    }

    /**
     * 弹幕蒙板文件头部大小
     *
     * Generated from protobuf field <code>double HeadLen = 8;</code>
     * @return float
     */
    public function getHeadLen()
    {
        return $this->HeadLen;
    }

    /**
     * 弹幕蒙板文件头部大小
     *
     * Generated from protobuf field <code>double HeadLen = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setHeadLen($var)
    {
        GPBUtil::checkDouble($var);
        $this->HeadLen = $var;

        return $this;
    }

}

