<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_upload.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.CommitUploadInfoParam</code>
 */
class CommitUploadInfoParam extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     */
    protected $SpaceName = '';
    /**
     * Generated from protobuf field <code>string CallbackArgs = 2;</code>
     */
    protected $CallbackArgs = '';
    /**
     * Generated from protobuf field <code>string SessionKey = 3;</code>
     */
    protected $SessionKey = '';
    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodUploadFunction Functions = 4;</code>
     */
    private $Functions;
    /**
     * Generated from protobuf field <code>string GetMetaMode = 5;</code>
     */
    protected $GetMetaMode = '';
    /**
     * Generated from protobuf field <code>string VodUploadSource = 6;</code>
     */
    protected $VodUploadSource = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $SpaceName
     *     @type string $CallbackArgs
     *     @type string $SessionKey
     *     @type \Volc\Service\Vod\Models\Business\VodUploadFunction[]|\Google\Protobuf\Internal\RepeatedField $Functions
     *     @type string $GetMetaMode
     *     @type string $VodUploadSource
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     * @return string
     */
    public function getSpaceName()
    {
        return $this->SpaceName;
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SpaceName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CallbackArgs = 2;</code>
     * @return string
     */
    public function getCallbackArgs()
    {
        return $this->CallbackArgs;
    }

    /**
     * Generated from protobuf field <code>string CallbackArgs = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCallbackArgs($var)
    {
        GPBUtil::checkString($var, True);
        $this->CallbackArgs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SessionKey = 3;</code>
     * @return string
     */
    public function getSessionKey()
    {
        return $this->SessionKey;
    }

    /**
     * Generated from protobuf field <code>string SessionKey = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->SessionKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodUploadFunction Functions = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFunctions()
    {
        return $this->Functions;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodUploadFunction Functions = 4;</code>
     * @param \Volc\Service\Vod\Models\Business\VodUploadFunction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFunctions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Service\Vod\Models\Business\VodUploadFunction::class);
        $this->Functions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string GetMetaMode = 5;</code>
     * @return string
     */
    public function getGetMetaMode()
    {
        return $this->GetMetaMode;
    }

    /**
     * Generated from protobuf field <code>string GetMetaMode = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setGetMetaMode($var)
    {
        GPBUtil::checkString($var, True);
        $this->GetMetaMode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string VodUploadSource = 6;</code>
     * @return string
     */
    public function getVodUploadSource()
    {
        return $this->VodUploadSource;
    }

    /**
     * Generated from protobuf field <code>string VodUploadSource = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setVodUploadSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->VodUploadSource = $var;

        return $this;
    }

}

