<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_cdn.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.CommonGlobalConfig</code>
 */
class CommonGlobalConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string ConfigName = 1;</code>
     */
    protected $ConfigName = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ConfigName
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string ConfigName = 1;</code>
     * @return string
     */
    public function getConfigName()
    {
        return isset($this->ConfigName) ? $this->ConfigName : '';
    }

    public function hasConfigName()
    {
        return isset($this->ConfigName);
    }

    public function clearConfigName()
    {
        unset($this->ConfigName);
    }

    /**
     * Generated from protobuf field <code>optional string ConfigName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConfigName($var)
    {
        GPBUtil::checkString($var, True);
        $this->ConfigName = $var;

        return $this;
    }

}

