<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_cdn.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.Compression</code>
 */
class Compression extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.CompressionRule CompressionRules = 1;</code>
     */
    private $CompressionRules;
    /**
     * Generated from protobuf field <code>optional bool Switch = 2;</code>
     */
    protected $Switch = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Volc\Service\Vod\Models\Business\CompressionRule[]|\Google\Protobuf\Internal\RepeatedField $CompressionRules
     *     @type bool $Switch
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.CompressionRule CompressionRules = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCompressionRules()
    {
        return $this->CompressionRules;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.CompressionRule CompressionRules = 1;</code>
     * @param \Volc\Service\Vod\Models\Business\CompressionRule[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCompressionRules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Service\Vod\Models\Business\CompressionRule::class);
        $this->CompressionRules = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool Switch = 2;</code>
     * @return bool
     */
    public function getSwitch()
    {
        return isset($this->Switch) ? $this->Switch : false;
    }

    public function hasSwitch()
    {
        return isset($this->Switch);
    }

    public function clearSwitch()
    {
        unset($this->Switch);
    }

    /**
     * Generated from protobuf field <code>optional bool Switch = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSwitch($var)
    {
        GPBUtil::checkBool($var);
        $this->Switch = $var;

        return $this;
    }

}

