<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_cdn.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.ConditionRule</code>
 */
class ConditionRule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Object = 1;</code>
     */
    protected $Object = null;
    /**
     * Generated from protobuf field <code>optional string Operator = 2;</code>
     */
    protected $Operator = null;
    /**
     * Generated from protobuf field <code>optional string Type = 3;</code>
     */
    protected $Type = null;
    /**
     * Generated from protobuf field <code>optional string Value = 4;</code>
     */
    protected $Value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Object
     *     @type string $Operator
     *     @type string $Type
     *     @type string $Value
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Object = 1;</code>
     * @return string
     */
    public function getObject()
    {
        return isset($this->Object) ? $this->Object : '';
    }

    public function hasObject()
    {
        return isset($this->Object);
    }

    public function clearObject()
    {
        unset($this->Object);
    }

    /**
     * Generated from protobuf field <code>optional string Object = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setObject($var)
    {
        GPBUtil::checkString($var, True);
        $this->Object = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Operator = 2;</code>
     * @return string
     */
    public function getOperator()
    {
        return isset($this->Operator) ? $this->Operator : '';
    }

    public function hasOperator()
    {
        return isset($this->Operator);
    }

    public function clearOperator()
    {
        unset($this->Operator);
    }

    /**
     * Generated from protobuf field <code>optional string Operator = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkString($var, True);
        $this->Operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Type = 3;</code>
     * @return string
     */
    public function getType()
    {
        return isset($this->Type) ? $this->Type : '';
    }

    public function hasType()
    {
        return isset($this->Type);
    }

    public function clearType()
    {
        unset($this->Type);
    }

    /**
     * Generated from protobuf field <code>optional string Type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Value = 4;</code>
     * @return string
     */
    public function getValue()
    {
        return isset($this->Value) ? $this->Value : '';
    }

    public function hasValue()
    {
        return isset($this->Value);
    }

    public function clearValue()
    {
        unset($this->Value);
    }

    /**
     * Generated from protobuf field <code>optional string Value = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->Value = $var;

        return $this;
    }

}

