<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_cdn.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.ContentTask</code>
 */
class ContentTask extends \Google\Protobuf\Internal\Message
{
    /**
     *代表一个内容 URL。
     *
     * Generated from protobuf field <code>string Url = 1;</code>
     */
    protected $Url = '';
    /**
     *代表一个内容 URL 的状态。该参数的可用值如下：
     *complete：已完成。
     *running：执行中。
     *failed：执行失败。
     *
     * Generated from protobuf field <code>string Status = 2;</code>
     */
    protected $Status = '';
    /**
     *代表一个任务类型。该参数的可用值如下：：
     *block_url：封禁任务。
     *unblock_url：解封任务。
     *
     * Generated from protobuf field <code>string TaskType = 3;</code>
     */
    protected $TaskType = '';
    /**
     *代表一个任务的提交时间。时间格式是 Unix 时间戳。
     *
     * Generated from protobuf field <code>int64 CreateTime = 4;</code>
     */
    protected $CreateTime = 0;
    /**
     *代表一个任务 ID。
     *
     * Generated from protobuf field <code>string TaskID = 5;</code>
     */
    protected $TaskID = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Url
     *          代表一个内容 URL。
     *     @type string $Status
     *          代表一个内容 URL 的状态。该参数的可用值如下：
     *          complete：已完成。
     *          running：执行中。
     *          failed：执行失败。
     *     @type string $TaskType
     *          代表一个任务类型。该参数的可用值如下：：
     *          block_url：封禁任务。
     *          unblock_url：解封任务。
     *     @type int|string $CreateTime
     *          代表一个任务的提交时间。时间格式是 Unix 时间戳。
     *     @type string $TaskID
     *          代表一个任务 ID。
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     *代表一个内容 URL。
     *
     * Generated from protobuf field <code>string Url = 1;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->Url;
    }

    /**
     *代表一个内容 URL。
     *
     * Generated from protobuf field <code>string Url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->Url = $var;

        return $this;
    }

    /**
     *代表一个内容 URL 的状态。该参数的可用值如下：
     *complete：已完成。
     *running：执行中。
     *failed：执行失败。
     *
     * Generated from protobuf field <code>string Status = 2;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     *代表一个内容 URL 的状态。该参数的可用值如下：
     *complete：已完成。
     *running：执行中。
     *failed：执行失败。
     *
     * Generated from protobuf field <code>string Status = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->Status = $var;

        return $this;
    }

    /**
     *代表一个任务类型。该参数的可用值如下：：
     *block_url：封禁任务。
     *unblock_url：解封任务。
     *
     * Generated from protobuf field <code>string TaskType = 3;</code>
     * @return string
     */
    public function getTaskType()
    {
        return $this->TaskType;
    }

    /**
     *代表一个任务类型。该参数的可用值如下：：
     *block_url：封禁任务。
     *unblock_url：解封任务。
     *
     * Generated from protobuf field <code>string TaskType = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskType($var)
    {
        GPBUtil::checkString($var, True);
        $this->TaskType = $var;

        return $this;
    }

    /**
     *代表一个任务的提交时间。时间格式是 Unix 时间戳。
     *
     * Generated from protobuf field <code>int64 CreateTime = 4;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->CreateTime;
    }

    /**
     *代表一个任务的提交时间。时间格式是 Unix 时间戳。
     *
     * Generated from protobuf field <code>int64 CreateTime = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->CreateTime = $var;

        return $this;
    }

    /**
     *代表一个任务 ID。
     *
     * Generated from protobuf field <code>string TaskID = 5;</code>
     * @return string
     */
    public function getTaskID()
    {
        return $this->TaskID;
    }

    /**
     *代表一个任务 ID。
     *
     * Generated from protobuf field <code>string TaskID = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskID($var)
    {
        GPBUtil::checkString($var, True);
        $this->TaskID = $var;

        return $this;
    }

}

