<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_measure.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.DescribeVodSpaceAIStatisDataResult</code>
 */
class DescribeVodSpaceAIStatisDataResult extends \Google\Protobuf\Internal\Message
{
    /**
     * 空间列表
     *
     * Generated from protobuf field <code>repeated string SpaceList = 1;</code>
     */
    private $SpaceList;
    /**
     * 查询的起始时间, rfc3339
     *
     * Generated from protobuf field <code>string StartTime = 2;</code>
     */
    protected $StartTime = '';
    /**
     * 查询的结束时间, rfc3339；查询时间跨度不超过93天
     *
     * Generated from protobuf field <code>string EndTime = 3;</code>
     */
    protected $EndTime = '';
    /**
     *类型：默认全部。VideoClassification(视频分类)，AIVideoSummary(精彩剪辑)，BarrageMask(蒙版弹幕)
     *
     * Generated from protobuf field <code>string MediaAiType = 4;</code>
     */
    protected $MediaAiType = '';
    /**
     * 闲忙时: busy/free
     *
     * Generated from protobuf field <code>repeated string TaskStageList = 5;</code>
     */
    private $TaskStageList;
    /**
     *聚合的时间粒度，单位秒，默认3600，支持3600和86400
     *
     * Generated from protobuf field <code>int64 Aggregation = 6;</code>
     */
    protected $Aggregation = 0;
    /**
     * 展示详细信息的维度，取值：TaskStage、Space
     *
     * Generated from protobuf field <code>repeated string DetailFieldList = 7;</code>
     */
    private $DetailFieldList;
    /**
     * Generated from protobuf field <code>repeated string RegionList = 8;</code>
     */
    private $RegionList;
    /**
     * Generated from protobuf field <code>int64 TotalAiUsageData = 9;</code>
     */
    protected $TotalAiUsageData = 0;
    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.DescribeVodSpaceAIStatisDataItem AiUsageDataList = 10;</code>
     */
    private $AiUsageDataList;
    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.DescribeVodSpaceAIStatisDataDetail AiUsageDataDetailList = 11;</code>
     */
    private $AiUsageDataDetailList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $SpaceList
     *           空间列表
     *     @type string $StartTime
     *           查询的起始时间, rfc3339
     *     @type string $EndTime
     *           查询的结束时间, rfc3339；查询时间跨度不超过93天
     *     @type string $MediaAiType
     *          类型：默认全部。VideoClassification(视频分类)，AIVideoSummary(精彩剪辑)，BarrageMask(蒙版弹幕)
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $TaskStageList
     *           闲忙时: busy/free
     *     @type int|string $Aggregation
     *          聚合的时间粒度，单位秒，默认3600，支持3600和86400
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $DetailFieldList
     *           展示详细信息的维度，取值：TaskStage、Space
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $RegionList
     *     @type int|string $TotalAiUsageData
     *     @type \Volc\Service\Vod\Models\Business\DescribeVodSpaceAIStatisDataItem[]|\Google\Protobuf\Internal\RepeatedField $AiUsageDataList
     *     @type \Volc\Service\Vod\Models\Business\DescribeVodSpaceAIStatisDataDetail[]|\Google\Protobuf\Internal\RepeatedField $AiUsageDataDetailList
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodMeasure::initOnce();
        parent::__construct($data);
    }

    /**
     * 空间列表
     *
     * Generated from protobuf field <code>repeated string SpaceList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpaceList()
    {
        return $this->SpaceList;
    }

    /**
     * 空间列表
     *
     * Generated from protobuf field <code>repeated string SpaceList = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpaceList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->SpaceList = $arr;

        return $this;
    }

    /**
     * 查询的起始时间, rfc3339
     *
     * Generated from protobuf field <code>string StartTime = 2;</code>
     * @return string
     */
    public function getStartTime()
    {
        return $this->StartTime;
    }

    /**
     * 查询的起始时间, rfc3339
     *
     * Generated from protobuf field <code>string StartTime = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->StartTime = $var;

        return $this;
    }

    /**
     * 查询的结束时间, rfc3339；查询时间跨度不超过93天
     *
     * Generated from protobuf field <code>string EndTime = 3;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->EndTime;
    }

    /**
     * 查询的结束时间, rfc3339；查询时间跨度不超过93天
     *
     * Generated from protobuf field <code>string EndTime = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->EndTime = $var;

        return $this;
    }

    /**
     *类型：默认全部。VideoClassification(视频分类)，AIVideoSummary(精彩剪辑)，BarrageMask(蒙版弹幕)
     *
     * Generated from protobuf field <code>string MediaAiType = 4;</code>
     * @return string
     */
    public function getMediaAiType()
    {
        return $this->MediaAiType;
    }

    /**
     *类型：默认全部。VideoClassification(视频分类)，AIVideoSummary(精彩剪辑)，BarrageMask(蒙版弹幕)
     *
     * Generated from protobuf field <code>string MediaAiType = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMediaAiType($var)
    {
        GPBUtil::checkString($var, True);
        $this->MediaAiType = $var;

        return $this;
    }

    /**
     * 闲忙时: busy/free
     *
     * Generated from protobuf field <code>repeated string TaskStageList = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTaskStageList()
    {
        return $this->TaskStageList;
    }

    /**
     * 闲忙时: busy/free
     *
     * Generated from protobuf field <code>repeated string TaskStageList = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTaskStageList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->TaskStageList = $arr;

        return $this;
    }

    /**
     *聚合的时间粒度，单位秒，默认3600，支持3600和86400
     *
     * Generated from protobuf field <code>int64 Aggregation = 6;</code>
     * @return int|string
     */
    public function getAggregation()
    {
        return $this->Aggregation;
    }

    /**
     *聚合的时间粒度，单位秒，默认3600，支持3600和86400
     *
     * Generated from protobuf field <code>int64 Aggregation = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAggregation($var)
    {
        GPBUtil::checkInt64($var);
        $this->Aggregation = $var;

        return $this;
    }

    /**
     * 展示详细信息的维度，取值：TaskStage、Space
     *
     * Generated from protobuf field <code>repeated string DetailFieldList = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDetailFieldList()
    {
        return $this->DetailFieldList;
    }

    /**
     * 展示详细信息的维度，取值：TaskStage、Space
     *
     * Generated from protobuf field <code>repeated string DetailFieldList = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDetailFieldList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DetailFieldList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string RegionList = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRegionList()
    {
        return $this->RegionList;
    }

    /**
     * Generated from protobuf field <code>repeated string RegionList = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRegionList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->RegionList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TotalAiUsageData = 9;</code>
     * @return int|string
     */
    public function getTotalAiUsageData()
    {
        return $this->TotalAiUsageData;
    }

    /**
     * Generated from protobuf field <code>int64 TotalAiUsageData = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalAiUsageData($var)
    {
        GPBUtil::checkInt64($var);
        $this->TotalAiUsageData = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.DescribeVodSpaceAIStatisDataItem AiUsageDataList = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAiUsageDataList()
    {
        return $this->AiUsageDataList;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.DescribeVodSpaceAIStatisDataItem AiUsageDataList = 10;</code>
     * @param \Volc\Service\Vod\Models\Business\DescribeVodSpaceAIStatisDataItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAiUsageDataList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Service\Vod\Models\Business\DescribeVodSpaceAIStatisDataItem::class);
        $this->AiUsageDataList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.DescribeVodSpaceAIStatisDataDetail AiUsageDataDetailList = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAiUsageDataDetailList()
    {
        return $this->AiUsageDataDetailList;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.DescribeVodSpaceAIStatisDataDetail AiUsageDataDetailList = 11;</code>
     * @param \Volc\Service\Vod\Models\Business\DescribeVodSpaceAIStatisDataDetail[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAiUsageDataDetailList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Service\Vod\Models\Business\DescribeVodSpaceAIStatisDataDetail::class);
        $this->AiUsageDataDetailList = $arr;

        return $this;
    }

}

