<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_cdn.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.DownloadSpeedLimitAction</code>
 */
class DownloadSpeedLimitAction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int64 SpeedLimitRate = 1;</code>
     */
    protected $SpeedLimitRate = null;
    /**
     * Generated from protobuf field <code>optional int64 SpeedLimitRateAfter = 2;</code>
     */
    protected $SpeedLimitRateAfter = null;
    /**
     * Generated from protobuf field <code>optional .Volcengine.Vod.Models.Business.SpeedLimitTime SpeedLimitTime = 3;</code>
     */
    protected $SpeedLimitTime = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $SpeedLimitRate
     *     @type int|string $SpeedLimitRateAfter
     *     @type \Volc\Service\Vod\Models\Business\SpeedLimitTime $SpeedLimitTime
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int64 SpeedLimitRate = 1;</code>
     * @return int|string
     */
    public function getSpeedLimitRate()
    {
        return isset($this->SpeedLimitRate) ? $this->SpeedLimitRate : 0;
    }

    public function hasSpeedLimitRate()
    {
        return isset($this->SpeedLimitRate);
    }

    public function clearSpeedLimitRate()
    {
        unset($this->SpeedLimitRate);
    }

    /**
     * Generated from protobuf field <code>optional int64 SpeedLimitRate = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSpeedLimitRate($var)
    {
        GPBUtil::checkInt64($var);
        $this->SpeedLimitRate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 SpeedLimitRateAfter = 2;</code>
     * @return int|string
     */
    public function getSpeedLimitRateAfter()
    {
        return isset($this->SpeedLimitRateAfter) ? $this->SpeedLimitRateAfter : 0;
    }

    public function hasSpeedLimitRateAfter()
    {
        return isset($this->SpeedLimitRateAfter);
    }

    public function clearSpeedLimitRateAfter()
    {
        unset($this->SpeedLimitRateAfter);
    }

    /**
     * Generated from protobuf field <code>optional int64 SpeedLimitRateAfter = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSpeedLimitRateAfter($var)
    {
        GPBUtil::checkInt64($var);
        $this->SpeedLimitRateAfter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Volcengine.Vod.Models.Business.SpeedLimitTime SpeedLimitTime = 3;</code>
     * @return \Volc\Service\Vod\Models\Business\SpeedLimitTime|null
     */
    public function getSpeedLimitTime()
    {
        return $this->SpeedLimitTime;
    }

    public function hasSpeedLimitTime()
    {
        return isset($this->SpeedLimitTime);
    }

    public function clearSpeedLimitTime()
    {
        unset($this->SpeedLimitTime);
    }

    /**
     * Generated from protobuf field <code>optional .Volcengine.Vod.Models.Business.SpeedLimitTime SpeedLimitTime = 3;</code>
     * @param \Volc\Service\Vod\Models\Business\SpeedLimitTime $var
     * @return $this
     */
    public function setSpeedLimitTime($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\SpeedLimitTime::class);
        $this->SpeedLimitTime = $var;

        return $this;
    }

}

