<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_edit.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.GetVCreativeTaskResult</code>
 */
class GetVCreativeTaskResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Uploader = 1;</code>
     */
    protected $Uploader = '';
    /**
     * Generated from protobuf field <code>string ParamJson = 2;</code>
     */
    protected $ParamJson = '';
    /**
     * Generated from protobuf field <code>string Status = 3;</code>
     */
    protected $Status = '';
    /**
     * Generated from protobuf field <code>string OutputJson = 4;</code>
     */
    protected $OutputJson = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Uploader
     *     @type string $ParamJson
     *     @type string $Status
     *     @type string $OutputJson
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodEdit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Uploader = 1;</code>
     * @return string
     */
    public function getUploader()
    {
        return $this->Uploader;
    }

    /**
     * Generated from protobuf field <code>string Uploader = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUploader($var)
    {
        GPBUtil::checkString($var, True);
        $this->Uploader = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ParamJson = 2;</code>
     * @return string
     */
    public function getParamJson()
    {
        return $this->ParamJson;
    }

    /**
     * Generated from protobuf field <code>string ParamJson = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParamJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParamJson = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Status = 3;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * Generated from protobuf field <code>string Status = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->Status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OutputJson = 4;</code>
     * @return string
     */
    public function getOutputJson()
    {
        return $this->OutputJson;
    }

    /**
     * Generated from protobuf field <code>string OutputJson = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOutputJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->OutputJson = $var;

        return $this;
    }

}

