<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_object.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.ObjectBlockTaskInfo</code>
 */
class ObjectBlockTaskInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *封禁状态 代表原站是否完成封禁
     *- forbid 封禁完成
     *- recover 已解封
     *- configuring 配置中
     *
     * Generated from protobuf field <code>string Status = 1;</code>
     */
    protected $Status = '';
    /**
     *任务Id
     *
     * Generated from protobuf field <code>string TaskId = 2;</code>
     */
    protected $TaskId = '';
    /**
     * Generated from protobuf field <code>string FileName = 3;</code>
     */
    protected $FileName = '';
    /**
     *刷新Cdn状态
     *- complete 可能部分成功
     *- running 刷新中
     *- waiting 原站封禁中 还未刷新
     *- notRequired 不需要刷新
     *
     * Generated from protobuf field <code>string RefreshStatus = 4;</code>
     */
    protected $RefreshStatus = '';
    /**
     *封禁状态 代表任务的类型
     *- forbid 封禁完成
     *- recover 已解封
     *
     * Generated from protobuf field <code>string Operation = 5;</code>
     */
    protected $Operation = '';
    /**
     *刷新任务Id
     *
     * Generated from protobuf field <code>string RefreshTaskId = 6;</code>
     */
    protected $RefreshTaskId = '';
    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.RefreshInfo RefreshInfos = 7;</code>
     */
    private $RefreshInfos;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Status
     *          封禁状态 代表原站是否完成封禁
     *          - forbid 封禁完成
     *          - recover 已解封
     *          - configuring 配置中
     *     @type string $TaskId
     *          任务Id
     *     @type string $FileName
     *     @type string $RefreshStatus
     *          刷新Cdn状态
     *          - complete 可能部分成功
     *          - running 刷新中
     *          - waiting 原站封禁中 还未刷新
     *          - notRequired 不需要刷新
     *     @type string $Operation
     *          封禁状态 代表任务的类型
     *          - forbid 封禁完成
     *          - recover 已解封
     *     @type string $RefreshTaskId
     *          刷新任务Id
     *     @type \Volc\Service\Vod\Models\Business\RefreshInfo[]|\Google\Protobuf\Internal\RepeatedField $RefreshInfos
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodObject::initOnce();
        parent::__construct($data);
    }

    /**
     *封禁状态 代表原站是否完成封禁
     *- forbid 封禁完成
     *- recover 已解封
     *- configuring 配置中
     *
     * Generated from protobuf field <code>string Status = 1;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     *封禁状态 代表原站是否完成封禁
     *- forbid 封禁完成
     *- recover 已解封
     *- configuring 配置中
     *
     * Generated from protobuf field <code>string Status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->Status = $var;

        return $this;
    }

    /**
     *任务Id
     *
     * Generated from protobuf field <code>string TaskId = 2;</code>
     * @return string
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     *任务Id
     *
     * Generated from protobuf field <code>string TaskId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->TaskId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FileName = 3;</code>
     * @return string
     */
    public function getFileName()
    {
        return $this->FileName;
    }

    /**
     * Generated from protobuf field <code>string FileName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->FileName = $var;

        return $this;
    }

    /**
     *刷新Cdn状态
     *- complete 可能部分成功
     *- running 刷新中
     *- waiting 原站封禁中 还未刷新
     *- notRequired 不需要刷新
     *
     * Generated from protobuf field <code>string RefreshStatus = 4;</code>
     * @return string
     */
    public function getRefreshStatus()
    {
        return $this->RefreshStatus;
    }

    /**
     *刷新Cdn状态
     *- complete 可能部分成功
     *- running 刷新中
     *- waiting 原站封禁中 还未刷新
     *- notRequired 不需要刷新
     *
     * Generated from protobuf field <code>string RefreshStatus = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->RefreshStatus = $var;

        return $this;
    }

    /**
     *封禁状态 代表任务的类型
     *- forbid 封禁完成
     *- recover 已解封
     *
     * Generated from protobuf field <code>string Operation = 5;</code>
     * @return string
     */
    public function getOperation()
    {
        return $this->Operation;
    }

    /**
     *封禁状态 代表任务的类型
     *- forbid 封禁完成
     *- recover 已解封
     *
     * Generated from protobuf field <code>string Operation = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOperation($var)
    {
        GPBUtil::checkString($var, True);
        $this->Operation = $var;

        return $this;
    }

    /**
     *刷新任务Id
     *
     * Generated from protobuf field <code>string RefreshTaskId = 6;</code>
     * @return string
     */
    public function getRefreshTaskId()
    {
        return $this->RefreshTaskId;
    }

    /**
     *刷新任务Id
     *
     * Generated from protobuf field <code>string RefreshTaskId = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RefreshTaskId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.RefreshInfo RefreshInfos = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRefreshInfos()
    {
        return $this->RefreshInfos;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.RefreshInfo RefreshInfos = 7;</code>
     * @param \Volc\Service\Vod\Models\Business\RefreshInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRefreshInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Service\Vod\Models\Business\RefreshInfo::class);
        $this->RefreshInfos = $arr;

        return $this;
    }

}

