<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_edit.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.Output</code>
 */
class Output extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool Alpha = 1;</code>
     */
    protected $Alpha = false;
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Codec Codec = 2;</code>
     */
    protected $Codec = null;
    /**
     * Generated from protobuf field <code>bool DisableAudio = 3;</code>
     */
    protected $DisableAudio = false;
    /**
     * Generated from protobuf field <code>bool DisableVideo = 4;</code>
     */
    protected $DisableVideo = false;
    /**
     * Generated from protobuf field <code>int32 Fps = 5;</code>
     */
    protected $Fps = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $Alpha
     *     @type \Volc\Service\Vod\Models\Business\Codec $Codec
     *     @type bool $DisableAudio
     *     @type bool $DisableVideo
     *     @type int $Fps
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodEdit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool Alpha = 1;</code>
     * @return bool
     */
    public function getAlpha()
    {
        return $this->Alpha;
    }

    /**
     * Generated from protobuf field <code>bool Alpha = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAlpha($var)
    {
        GPBUtil::checkBool($var);
        $this->Alpha = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Codec Codec = 2;</code>
     * @return \Volc\Service\Vod\Models\Business\Codec|null
     */
    public function getCodec()
    {
        return $this->Codec;
    }

    public function hasCodec()
    {
        return isset($this->Codec);
    }

    public function clearCodec()
    {
        unset($this->Codec);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Codec Codec = 2;</code>
     * @param \Volc\Service\Vod\Models\Business\Codec $var
     * @return $this
     */
    public function setCodec($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\Codec::class);
        $this->Codec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool DisableAudio = 3;</code>
     * @return bool
     */
    public function getDisableAudio()
    {
        return $this->DisableAudio;
    }

    /**
     * Generated from protobuf field <code>bool DisableAudio = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisableAudio($var)
    {
        GPBUtil::checkBool($var);
        $this->DisableAudio = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool DisableVideo = 4;</code>
     * @return bool
     */
    public function getDisableVideo()
    {
        return $this->DisableVideo;
    }

    /**
     * Generated from protobuf field <code>bool DisableVideo = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisableVideo($var)
    {
        GPBUtil::checkBool($var);
        $this->DisableVideo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Fps = 5;</code>
     * @return int
     */
    public function getFps()
    {
        return $this->Fps;
    }

    /**
     * Generated from protobuf field <code>int32 Fps = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setFps($var)
    {
        GPBUtil::checkInt32($var);
        $this->Fps = $var;

        return $this;
    }

}

