<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_workflow.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.SnapshotTaskParams</code>
 */
class SnapshotTaskParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Type = 1;</code>
     */
    protected $Type = '';
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.PosterSnapshotParams PosterSnapshotParams = 2;</code>
     */
    protected $PosterSnapshotParams = null;
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.DynpostSnapshotParams DynpostSnapshotParams = 3;</code>
     */
    protected $DynpostSnapshotParams = null;
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.AnimatedPosterSnapshotParams AnimatedPosterSnapshotParams = 4;</code>
     */
    protected $AnimatedPosterSnapshotParams = null;
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.SpriteSnapshotParams SpriteSnapshotParams = 5;</code>
     */
    protected $SpriteSnapshotParams = null;
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.SampleSnapshotParams SampleSnapshotParams = 7;</code>
     */
    protected $SampleSnapshotParams = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Type
     *     @type \Volc\Service\Vod\Models\Business\PosterSnapshotParams $PosterSnapshotParams
     *     @type \Volc\Service\Vod\Models\Business\DynpostSnapshotParams $DynpostSnapshotParams
     *     @type \Volc\Service\Vod\Models\Business\AnimatedPosterSnapshotParams $AnimatedPosterSnapshotParams
     *     @type \Volc\Service\Vod\Models\Business\SpriteSnapshotParams $SpriteSnapshotParams
     *     @type \Volc\Service\Vod\Models\Business\SampleSnapshotParams $SampleSnapshotParams
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodWorkflow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>string Type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.PosterSnapshotParams PosterSnapshotParams = 2;</code>
     * @return \Volc\Service\Vod\Models\Business\PosterSnapshotParams|null
     */
    public function getPosterSnapshotParams()
    {
        return $this->PosterSnapshotParams;
    }

    public function hasPosterSnapshotParams()
    {
        return isset($this->PosterSnapshotParams);
    }

    public function clearPosterSnapshotParams()
    {
        unset($this->PosterSnapshotParams);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.PosterSnapshotParams PosterSnapshotParams = 2;</code>
     * @param \Volc\Service\Vod\Models\Business\PosterSnapshotParams $var
     * @return $this
     */
    public function setPosterSnapshotParams($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\PosterSnapshotParams::class);
        $this->PosterSnapshotParams = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.DynpostSnapshotParams DynpostSnapshotParams = 3;</code>
     * @return \Volc\Service\Vod\Models\Business\DynpostSnapshotParams|null
     */
    public function getDynpostSnapshotParams()
    {
        return $this->DynpostSnapshotParams;
    }

    public function hasDynpostSnapshotParams()
    {
        return isset($this->DynpostSnapshotParams);
    }

    public function clearDynpostSnapshotParams()
    {
        unset($this->DynpostSnapshotParams);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.DynpostSnapshotParams DynpostSnapshotParams = 3;</code>
     * @param \Volc\Service\Vod\Models\Business\DynpostSnapshotParams $var
     * @return $this
     */
    public function setDynpostSnapshotParams($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\DynpostSnapshotParams::class);
        $this->DynpostSnapshotParams = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.AnimatedPosterSnapshotParams AnimatedPosterSnapshotParams = 4;</code>
     * @return \Volc\Service\Vod\Models\Business\AnimatedPosterSnapshotParams|null
     */
    public function getAnimatedPosterSnapshotParams()
    {
        return $this->AnimatedPosterSnapshotParams;
    }

    public function hasAnimatedPosterSnapshotParams()
    {
        return isset($this->AnimatedPosterSnapshotParams);
    }

    public function clearAnimatedPosterSnapshotParams()
    {
        unset($this->AnimatedPosterSnapshotParams);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.AnimatedPosterSnapshotParams AnimatedPosterSnapshotParams = 4;</code>
     * @param \Volc\Service\Vod\Models\Business\AnimatedPosterSnapshotParams $var
     * @return $this
     */
    public function setAnimatedPosterSnapshotParams($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\AnimatedPosterSnapshotParams::class);
        $this->AnimatedPosterSnapshotParams = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.SpriteSnapshotParams SpriteSnapshotParams = 5;</code>
     * @return \Volc\Service\Vod\Models\Business\SpriteSnapshotParams|null
     */
    public function getSpriteSnapshotParams()
    {
        return $this->SpriteSnapshotParams;
    }

    public function hasSpriteSnapshotParams()
    {
        return isset($this->SpriteSnapshotParams);
    }

    public function clearSpriteSnapshotParams()
    {
        unset($this->SpriteSnapshotParams);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.SpriteSnapshotParams SpriteSnapshotParams = 5;</code>
     * @param \Volc\Service\Vod\Models\Business\SpriteSnapshotParams $var
     * @return $this
     */
    public function setSpriteSnapshotParams($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\SpriteSnapshotParams::class);
        $this->SpriteSnapshotParams = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.SampleSnapshotParams SampleSnapshotParams = 7;</code>
     * @return \Volc\Service\Vod\Models\Business\SampleSnapshotParams|null
     */
    public function getSampleSnapshotParams()
    {
        return $this->SampleSnapshotParams;
    }

    public function hasSampleSnapshotParams()
    {
        return isset($this->SampleSnapshotParams);
    }

    public function clearSampleSnapshotParams()
    {
        unset($this->SampleSnapshotParams);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.SampleSnapshotParams SampleSnapshotParams = 7;</code>
     * @param \Volc\Service\Vod\Models\Business\SampleSnapshotParams $var
     * @return $this
     */
    public function setSampleSnapshotParams($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\SampleSnapshotParams::class);
        $this->SampleSnapshotParams = $var;

        return $this;
    }

}

