<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_cdn.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.SpeedLimitTime</code>
 */
class SpeedLimitTime extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string BeginTime = 1;</code>
     */
    protected $BeginTime = null;
    /**
     * Generated from protobuf field <code>optional string DayWeek = 2;</code>
     */
    protected $DayWeek = null;
    /**
     * Generated from protobuf field <code>optional string EndTime = 3;</code>
     */
    protected $EndTime = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $BeginTime
     *     @type string $DayWeek
     *     @type string $EndTime
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string BeginTime = 1;</code>
     * @return string
     */
    public function getBeginTime()
    {
        return isset($this->BeginTime) ? $this->BeginTime : '';
    }

    public function hasBeginTime()
    {
        return isset($this->BeginTime);
    }

    public function clearBeginTime()
    {
        unset($this->BeginTime);
    }

    /**
     * Generated from protobuf field <code>optional string BeginTime = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBeginTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->BeginTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string DayWeek = 2;</code>
     * @return string
     */
    public function getDayWeek()
    {
        return isset($this->DayWeek) ? $this->DayWeek : '';
    }

    public function hasDayWeek()
    {
        return isset($this->DayWeek);
    }

    public function clearDayWeek()
    {
        unset($this->DayWeek);
    }

    /**
     * Generated from protobuf field <code>optional string DayWeek = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDayWeek($var)
    {
        GPBUtil::checkString($var, True);
        $this->DayWeek = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string EndTime = 3;</code>
     * @return string
     */
    public function getEndTime()
    {
        return isset($this->EndTime) ? $this->EndTime : '';
    }

    public function hasEndTime()
    {
        return isset($this->EndTime);
    }

    public function clearEndTime()
    {
        unset($this->EndTime);
    }

    /**
     * Generated from protobuf field <code>optional string EndTime = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->EndTime = $var;

        return $this;
    }

}

