<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_upload.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.SubmitMoveObjectTaskParam</code>
 */
class SubmitMoveObjectTaskParam extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string SourceSpace = 1;</code>
     */
    protected $SourceSpace = '';
    /**
     * Generated from protobuf field <code>string SourceFileName = 2;</code>
     */
    protected $SourceFileName = '';
    /**
     * Generated from protobuf field <code>string TargetSpace = 3;</code>
     */
    protected $TargetSpace = '';
    /**
     * Generated from protobuf field <code>string TargetFileName = 4;</code>
     */
    protected $TargetFileName = '';
    /**
     * Generated from protobuf field <code>bool SaveSourceObject = 5;</code>
     */
    protected $SaveSourceObject = false;
    /**
     * Generated from protobuf field <code>bool ForceOverwrite = 6;</code>
     */
    protected $ForceOverwrite = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $SourceSpace
     *     @type string $SourceFileName
     *     @type string $TargetSpace
     *     @type string $TargetFileName
     *     @type bool $SaveSourceObject
     *     @type bool $ForceOverwrite
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string SourceSpace = 1;</code>
     * @return string
     */
    public function getSourceSpace()
    {
        return $this->SourceSpace;
    }

    /**
     * Generated from protobuf field <code>string SourceSpace = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceSpace($var)
    {
        GPBUtil::checkString($var, True);
        $this->SourceSpace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SourceFileName = 2;</code>
     * @return string
     */
    public function getSourceFileName()
    {
        return $this->SourceFileName;
    }

    /**
     * Generated from protobuf field <code>string SourceFileName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SourceFileName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TargetSpace = 3;</code>
     * @return string
     */
    public function getTargetSpace()
    {
        return $this->TargetSpace;
    }

    /**
     * Generated from protobuf field <code>string TargetSpace = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetSpace($var)
    {
        GPBUtil::checkString($var, True);
        $this->TargetSpace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TargetFileName = 4;</code>
     * @return string
     */
    public function getTargetFileName()
    {
        return $this->TargetFileName;
    }

    /**
     * Generated from protobuf field <code>string TargetFileName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->TargetFileName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool SaveSourceObject = 5;</code>
     * @return bool
     */
    public function getSaveSourceObject()
    {
        return $this->SaveSourceObject;
    }

    /**
     * Generated from protobuf field <code>bool SaveSourceObject = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setSaveSourceObject($var)
    {
        GPBUtil::checkBool($var);
        $this->SaveSourceObject = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ForceOverwrite = 6;</code>
     * @return bool
     */
    public function getForceOverwrite()
    {
        return $this->ForceOverwrite;
    }

    /**
     * Generated from protobuf field <code>bool ForceOverwrite = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setForceOverwrite($var)
    {
        GPBUtil::checkBool($var);
        $this->ForceOverwrite = $var;

        return $this;
    }

}

