<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_workflow.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.TextLogoDefinition</code>
 */
class TextLogoDefinition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Content = 1;</code>
     */
    protected $Content = '';
    /**
     * Generated from protobuf field <code>string FontType = 2;</code>
     */
    protected $FontType = '';
    /**
     * Generated from protobuf field <code>int32 FontSize = 3;</code>
     */
    protected $FontSize = 0;
    /**
     * Generated from protobuf field <code>string FontColor = 4;</code>
     */
    protected $FontColor = '';
    /**
     * Generated from protobuf field <code>int32 StartTime = 5;</code>
     */
    protected $StartTime = 0;
    /**
     * Generated from protobuf field <code>int32 EndTime = 6;</code>
     */
    protected $EndTime = 0;
    /**
     * Generated from protobuf field <code>string Locate = 7;</code>
     */
    protected $Locate = '';
    /**
     * Generated from protobuf field <code>int32 PosX = 8;</code>
     */
    protected $PosX = 0;
    /**
     * Generated from protobuf field <code>int32 PosY = 9;</code>
     */
    protected $PosY = 0;
    /**
     * Generated from protobuf field <code>int32 SizeX = 10;</code>
     */
    protected $SizeX = 0;
    /**
     * Generated from protobuf field <code>int32 SizeY = 11;</code>
     */
    protected $SizeY = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Content
     *     @type string $FontType
     *     @type int $FontSize
     *     @type string $FontColor
     *     @type int $StartTime
     *     @type int $EndTime
     *     @type string $Locate
     *     @type int $PosX
     *     @type int $PosY
     *     @type int $SizeX
     *     @type int $SizeY
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodWorkflow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Content = 1;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * Generated from protobuf field <code>string Content = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->Content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FontType = 2;</code>
     * @return string
     */
    public function getFontType()
    {
        return $this->FontType;
    }

    /**
     * Generated from protobuf field <code>string FontType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFontType($var)
    {
        GPBUtil::checkString($var, True);
        $this->FontType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 FontSize = 3;</code>
     * @return int
     */
    public function getFontSize()
    {
        return $this->FontSize;
    }

    /**
     * Generated from protobuf field <code>int32 FontSize = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFontSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->FontSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FontColor = 4;</code>
     * @return string
     */
    public function getFontColor()
    {
        return $this->FontColor;
    }

    /**
     * Generated from protobuf field <code>string FontColor = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFontColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->FontColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 StartTime = 5;</code>
     * @return int
     */
    public function getStartTime()
    {
        return $this->StartTime;
    }

    /**
     * Generated from protobuf field <code>int32 StartTime = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->StartTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 EndTime = 6;</code>
     * @return int
     */
    public function getEndTime()
    {
        return $this->EndTime;
    }

    /**
     * Generated from protobuf field <code>int32 EndTime = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->EndTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Locate = 7;</code>
     * @return string
     */
    public function getLocate()
    {
        return $this->Locate;
    }

    /**
     * Generated from protobuf field <code>string Locate = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setLocate($var)
    {
        GPBUtil::checkString($var, True);
        $this->Locate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 PosX = 8;</code>
     * @return int
     */
    public function getPosX()
    {
        return $this->PosX;
    }

    /**
     * Generated from protobuf field <code>int32 PosX = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setPosX($var)
    {
        GPBUtil::checkInt32($var);
        $this->PosX = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 PosY = 9;</code>
     * @return int
     */
    public function getPosY()
    {
        return $this->PosY;
    }

    /**
     * Generated from protobuf field <code>int32 PosY = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setPosY($var)
    {
        GPBUtil::checkInt32($var);
        $this->PosY = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 SizeX = 10;</code>
     * @return int
     */
    public function getSizeX()
    {
        return $this->SizeX;
    }

    /**
     * Generated from protobuf field <code>int32 SizeX = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setSizeX($var)
    {
        GPBUtil::checkInt32($var);
        $this->SizeX = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 SizeY = 11;</code>
     * @return int
     */
    public function getSizeY()
    {
        return $this->SizeY;
    }

    /**
     * Generated from protobuf field <code>int32 SizeY = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setSizeY($var)
    {
        GPBUtil::checkInt32($var);
        $this->SizeY = $var;

        return $this;
    }

}

