<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_workflow.proto

namespace Volc\Service\Vod\Models\Business;

if (false) {
    /**
     * This class is deprecated. Use Volc\Service\Vod\Models\Business\TranscodeActivity\SubtitleParams instead.
     * @deprecated
     */
    class TranscodeActivity_SubtitleParams {}
}
class_exists(TranscodeActivity\SubtitleParams::class);
@trigger_error('Volc\Service\Vod\Models\Business\TranscodeActivity_SubtitleParams is deprecated and will be removed in the next major release. Use Volc\Service\Vod\Models\Business\TranscodeActivity\SubtitleParams instead', E_USER_DEPRECATED);

