<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_workflow.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.TranscodeVideoTaskParams</code>
 */
class TranscodeVideoTaskParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string TranscodeTemplateType = 1;</code>
     */
    protected $TranscodeTemplateType = '';
    /**
     * Generated from protobuf field <code>string Container = 2;</code>
     */
    protected $Container = '';
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Video Video = 3;</code>
     */
    protected $Video = null;
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Audio Audio = 4;</code>
     */
    protected $Audio = null;
    /**
     * Generated from protobuf field <code>bool DisableAudio = 5;</code>
     */
    protected $DisableAudio = false;
    /**
     * Generated from protobuf field <code>string Quality = 6;</code>
     */
    protected $Quality = '';
    /**
     * Generated from protobuf field <code>string Vladder = 7;</code>
     */
    protected $Vladder = '';
    /**
     * Generated from protobuf field <code>string UserTag = 8;</code>
     */
    protected $UserTag = '';
    /**
     * Generated from protobuf field <code>bool Encrypt = 9;</code>
     */
    protected $Encrypt = false;
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Encryption Encryption = 10;</code>
     */
    protected $Encryption = null;
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Segment Segment = 11;</code>
     */
    protected $Segment = null;
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Volume Volume = 12;</code>
     */
    protected $Volume = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $TranscodeTemplateType
     *     @type string $Container
     *     @type \Volc\Service\Vod\Models\Business\Video $Video
     *     @type \Volc\Service\Vod\Models\Business\Audio $Audio
     *     @type bool $DisableAudio
     *     @type string $Quality
     *     @type string $Vladder
     *     @type string $UserTag
     *     @type bool $Encrypt
     *     @type \Volc\Service\Vod\Models\Business\Encryption $Encryption
     *     @type \Volc\Service\Vod\Models\Business\Segment $Segment
     *     @type \Volc\Service\Vod\Models\Business\Volume $Volume
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodWorkflow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string TranscodeTemplateType = 1;</code>
     * @return string
     */
    public function getTranscodeTemplateType()
    {
        return $this->TranscodeTemplateType;
    }

    /**
     * Generated from protobuf field <code>string TranscodeTemplateType = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTranscodeTemplateType($var)
    {
        GPBUtil::checkString($var, True);
        $this->TranscodeTemplateType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Container = 2;</code>
     * @return string
     */
    public function getContainer()
    {
        return $this->Container;
    }

    /**
     * Generated from protobuf field <code>string Container = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContainer($var)
    {
        GPBUtil::checkString($var, True);
        $this->Container = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Video Video = 3;</code>
     * @return \Volc\Service\Vod\Models\Business\Video|null
     */
    public function getVideo()
    {
        return $this->Video;
    }

    public function hasVideo()
    {
        return isset($this->Video);
    }

    public function clearVideo()
    {
        unset($this->Video);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Video Video = 3;</code>
     * @param \Volc\Service\Vod\Models\Business\Video $var
     * @return $this
     */
    public function setVideo($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\Video::class);
        $this->Video = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Audio Audio = 4;</code>
     * @return \Volc\Service\Vod\Models\Business\Audio|null
     */
    public function getAudio()
    {
        return $this->Audio;
    }

    public function hasAudio()
    {
        return isset($this->Audio);
    }

    public function clearAudio()
    {
        unset($this->Audio);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Audio Audio = 4;</code>
     * @param \Volc\Service\Vod\Models\Business\Audio $var
     * @return $this
     */
    public function setAudio($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\Audio::class);
        $this->Audio = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool DisableAudio = 5;</code>
     * @return bool
     */
    public function getDisableAudio()
    {
        return $this->DisableAudio;
    }

    /**
     * Generated from protobuf field <code>bool DisableAudio = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisableAudio($var)
    {
        GPBUtil::checkBool($var);
        $this->DisableAudio = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Quality = 6;</code>
     * @return string
     */
    public function getQuality()
    {
        return $this->Quality;
    }

    /**
     * Generated from protobuf field <code>string Quality = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setQuality($var)
    {
        GPBUtil::checkString($var, True);
        $this->Quality = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Vladder = 7;</code>
     * @return string
     */
    public function getVladder()
    {
        return $this->Vladder;
    }

    /**
     * Generated from protobuf field <code>string Vladder = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setVladder($var)
    {
        GPBUtil::checkString($var, True);
        $this->Vladder = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string UserTag = 8;</code>
     * @return string
     */
    public function getUserTag()
    {
        return $this->UserTag;
    }

    /**
     * Generated from protobuf field <code>string UserTag = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUserTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserTag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Encrypt = 9;</code>
     * @return bool
     */
    public function getEncrypt()
    {
        return $this->Encrypt;
    }

    /**
     * Generated from protobuf field <code>bool Encrypt = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setEncrypt($var)
    {
        GPBUtil::checkBool($var);
        $this->Encrypt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Encryption Encryption = 10;</code>
     * @return \Volc\Service\Vod\Models\Business\Encryption|null
     */
    public function getEncryption()
    {
        return $this->Encryption;
    }

    public function hasEncryption()
    {
        return isset($this->Encryption);
    }

    public function clearEncryption()
    {
        unset($this->Encryption);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Encryption Encryption = 10;</code>
     * @param \Volc\Service\Vod\Models\Business\Encryption $var
     * @return $this
     */
    public function setEncryption($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\Encryption::class);
        $this->Encryption = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Segment Segment = 11;</code>
     * @return \Volc\Service\Vod\Models\Business\Segment|null
     */
    public function getSegment()
    {
        return $this->Segment;
    }

    public function hasSegment()
    {
        return isset($this->Segment);
    }

    public function clearSegment()
    {
        unset($this->Segment);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Segment Segment = 11;</code>
     * @param \Volc\Service\Vod\Models\Business\Segment $var
     * @return $this
     */
    public function setSegment($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\Segment::class);
        $this->Segment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Volume Volume = 12;</code>
     * @return \Volc\Service\Vod\Models\Business\Volume|null
     */
    public function getVolume()
    {
        return $this->Volume;
    }

    public function hasVolume()
    {
        return isset($this->Volume);
    }

    public function clearVolume()
    {
        unset($this->Volume);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.Volume Volume = 12;</code>
     * @param \Volc\Service\Vod\Models\Business\Volume $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\Volume::class);
        $this->Volume = $var;

        return $this;
    }

}

