<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_workflow.proto

namespace Volc\Service\Vod\Models\Business;

if (false) {
    /**
     * This class is deprecated. Use Volc\Service\Vod\Models\Business\TranscodeActivity\EnhanceParams instead.
     * @deprecated
     */
    class TranscodeActivity_EnhanceParams {}
}
class_exists(TranscodeActivity\EnhanceParams::class);
@trigger_error('Volc\Service\Vod\Models\Business\TranscodeActivity_EnhanceParams is deprecated and will be removed in the next major release. Use Volc\Service\Vod\Models\Business\TranscodeActivity\EnhanceParams instead', E_USER_DEPRECATED);

