<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_upload.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.ValuePair</code>
 */
class ValuePair extends \Google\Protobuf\Internal\Message
{
    /**
     * Url对应的JobId 
     *
     * Generated from protobuf field <code>string JobId = 1;</code>
     */
    protected $JobId = '';
    /**
     * 用户上传的Url 
     *
     * Generated from protobuf field <code>string SourceUrl = 2;</code>
     */
    protected $SourceUrl = '';
    /**
     * 图集url 
     *
     * Generated from protobuf field <code>repeated string ImageUrls = 3;</code>
     */
    private $ImageUrls;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $JobId
     *           Url对应的JobId 
     *     @type string $SourceUrl
     *           用户上传的Url 
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $ImageUrls
     *           图集url 
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * Url对应的JobId 
     *
     * Generated from protobuf field <code>string JobId = 1;</code>
     * @return string
     */
    public function getJobId()
    {
        return $this->JobId;
    }

    /**
     * Url对应的JobId 
     *
     * Generated from protobuf field <code>string JobId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkString($var, True);
        $this->JobId = $var;

        return $this;
    }

    /**
     * 用户上传的Url 
     *
     * Generated from protobuf field <code>string SourceUrl = 2;</code>
     * @return string
     */
    public function getSourceUrl()
    {
        return $this->SourceUrl;
    }

    /**
     * 用户上传的Url 
     *
     * Generated from protobuf field <code>string SourceUrl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->SourceUrl = $var;

        return $this;
    }

    /**
     * 图集url 
     *
     * Generated from protobuf field <code>repeated string ImageUrls = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getImageUrls()
    {
        return $this->ImageUrls;
    }

    /**
     * 图集url 
     *
     * Generated from protobuf field <code>repeated string ImageUrls = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setImageUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ImageUrls = $arr;

        return $this;
    }

}

