<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_upload.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodApplyUploadInfoData</code>
 */
class VodApplyUploadInfoData extends \Google\Protobuf\Internal\Message
{
    /**
     * 1001 阶段返回信息 
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodUploadAddress UploadAddress = 1;</code>
     */
    protected $UploadAddress = null;
    /**
     * 1001 阶段返回候选上传地址用于降级 
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.CandidateUploadAddresses CandidateUploadAddresses = 2;</code>
     */
    protected $CandidateUploadAddresses = null;
    /**
     * 1001 阶段返回内网上传信息 
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VpcTosUploadAddress VpcTosUploadAddress = 3;</code>
     */
    protected $VpcTosUploadAddress = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Volc\Service\Vod\Models\Business\VodUploadAddress $UploadAddress
     *           1001 阶段返回信息 
     *     @type \Volc\Service\Vod\Models\Business\CandidateUploadAddresses $CandidateUploadAddresses
     *           1001 阶段返回候选上传地址用于降级 
     *     @type \Volc\Service\Vod\Models\Business\VpcTosUploadAddress $VpcTosUploadAddress
     *           1001 阶段返回内网上传信息 
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * 1001 阶段返回信息 
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodUploadAddress UploadAddress = 1;</code>
     * @return \Volc\Service\Vod\Models\Business\VodUploadAddress|null
     */
    public function getUploadAddress()
    {
        return $this->UploadAddress;
    }

    public function hasUploadAddress()
    {
        return isset($this->UploadAddress);
    }

    public function clearUploadAddress()
    {
        unset($this->UploadAddress);
    }

    /**
     * 1001 阶段返回信息 
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodUploadAddress UploadAddress = 1;</code>
     * @param \Volc\Service\Vod\Models\Business\VodUploadAddress $var
     * @return $this
     */
    public function setUploadAddress($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\VodUploadAddress::class);
        $this->UploadAddress = $var;

        return $this;
    }

    /**
     * 1001 阶段返回候选上传地址用于降级 
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.CandidateUploadAddresses CandidateUploadAddresses = 2;</code>
     * @return \Volc\Service\Vod\Models\Business\CandidateUploadAddresses|null
     */
    public function getCandidateUploadAddresses()
    {
        return $this->CandidateUploadAddresses;
    }

    public function hasCandidateUploadAddresses()
    {
        return isset($this->CandidateUploadAddresses);
    }

    public function clearCandidateUploadAddresses()
    {
        unset($this->CandidateUploadAddresses);
    }

    /**
     * 1001 阶段返回候选上传地址用于降级 
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.CandidateUploadAddresses CandidateUploadAddresses = 2;</code>
     * @param \Volc\Service\Vod\Models\Business\CandidateUploadAddresses $var
     * @return $this
     */
    public function setCandidateUploadAddresses($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\CandidateUploadAddresses::class);
        $this->CandidateUploadAddresses = $var;

        return $this;
    }

    /**
     * 1001 阶段返回内网上传信息 
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VpcTosUploadAddress VpcTosUploadAddress = 3;</code>
     * @return \Volc\Service\Vod\Models\Business\VpcTosUploadAddress|null
     */
    public function getVpcTosUploadAddress()
    {
        return $this->VpcTosUploadAddress;
    }

    public function hasVpcTosUploadAddress()
    {
        return isset($this->VpcTosUploadAddress);
    }

    public function clearVpcTosUploadAddress()
    {
        unset($this->VpcTosUploadAddress);
    }

    /**
     * 1001 阶段返回内网上传信息 
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VpcTosUploadAddress VpcTosUploadAddress = 3;</code>
     * @param \Volc\Service\Vod\Models\Business\VpcTosUploadAddress $var
     * @return $this
     */
    public function setVpcTosUploadAddress($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\VpcTosUploadAddress::class);
        $this->VpcTosUploadAddress = $var;

        return $this;
    }

}

