<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_drama.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodCreateDramaRecapTaskSpeakerConfig</code>
 */
class VodCreateDramaRecapTaskSpeakerConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string VoiceType = 1;</code>
     */
    protected $VoiceType = '';
    /**
     * Generated from protobuf field <code>string AppId = 2;</code>
     */
    protected $AppId = '';
    /**
     * Generated from protobuf field <code>optional string Cluster = 3;</code>
     */
    protected $Cluster = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $VoiceType
     *     @type string $AppId
     *     @type string $Cluster
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodDrama::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string VoiceType = 1;</code>
     * @return string
     */
    public function getVoiceType()
    {
        return $this->VoiceType;
    }

    /**
     * Generated from protobuf field <code>string VoiceType = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVoiceType($var)
    {
        GPBUtil::checkString($var, True);
        $this->VoiceType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string AppId = 2;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->AppId;
    }

    /**
     * Generated from protobuf field <code>string AppId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->AppId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Cluster = 3;</code>
     * @return string
     */
    public function getCluster()
    {
        return isset($this->Cluster) ? $this->Cluster : '';
    }

    public function hasCluster()
    {
        return isset($this->Cluster);
    }

    public function clearCluster()
    {
        unset($this->Cluster);
    }

    /**
     * Generated from protobuf field <code>optional string Cluster = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCluster($var)
    {
        GPBUtil::checkString($var, True);
        $this->Cluster = $var;

        return $this;
    }

}

