<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_migrate.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodCloudMigrateJobSourceInfo</code>
 */
class VodCloudMigrateJobSourceInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Vendor = 1;</code>
     */
    protected $Vendor = '';
    /**
     * Generated from protobuf field <code>string SourceAK = 2;</code>
     */
    protected $SourceAK = '';
    /**
     * Generated from protobuf field <code>string SourceSK = 3;</code>
     */
    protected $SourceSK = '';
    /**
     * Generated from protobuf field <code>string SourceDomain = 4;</code>
     */
    protected $SourceDomain = '';
    /**
     * Generated from protobuf field <code>string SourceDomainKey = 5;</code>
     */
    protected $SourceDomainKey = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Vendor
     *     @type string $SourceAK
     *     @type string $SourceSK
     *     @type string $SourceDomain
     *     @type string $SourceDomainKey
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodMigrate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Vendor = 1;</code>
     * @return string
     */
    public function getVendor()
    {
        return $this->Vendor;
    }

    /**
     * Generated from protobuf field <code>string Vendor = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVendor($var)
    {
        GPBUtil::checkString($var, True);
        $this->Vendor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SourceAK = 2;</code>
     * @return string
     */
    public function getSourceAK()
    {
        return $this->SourceAK;
    }

    /**
     * Generated from protobuf field <code>string SourceAK = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceAK($var)
    {
        GPBUtil::checkString($var, True);
        $this->SourceAK = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SourceSK = 3;</code>
     * @return string
     */
    public function getSourceSK()
    {
        return $this->SourceSK;
    }

    /**
     * Generated from protobuf field <code>string SourceSK = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceSK($var)
    {
        GPBUtil::checkString($var, True);
        $this->SourceSK = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SourceDomain = 4;</code>
     * @return string
     */
    public function getSourceDomain()
    {
        return $this->SourceDomain;
    }

    /**
     * Generated from protobuf field <code>string SourceDomain = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->SourceDomain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SourceDomainKey = 5;</code>
     * @return string
     */
    public function getSourceDomainKey()
    {
        return $this->SourceDomainKey;
    }

    /**
     * Generated from protobuf field <code>string SourceDomainKey = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceDomainKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->SourceDomainKey = $var;

        return $this;
    }

}

