<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_cdn.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodDescribeVodDomainBandwidthDataResult</code>
 */
class VodDescribeVodDomainBandwidthDataResult extends \Google\Protobuf\Internal\Message
{
    /**
     * 域名列表
     *
     * Generated from protobuf field <code>repeated string DomainList = 1;</code>
     */
    private $DomainList;
    /**
     * 域名列表
     *
     * Generated from protobuf field <code>repeated string DomainInSpaceList = 2;</code>
     */
    private $DomainInSpaceList;
    /**
     * 查询的起始时间
     *
     * Generated from protobuf field <code>string StartTime = 3;</code>
     */
    protected $StartTime = '';
    /**
     * 查询的结束时间
     *
     * Generated from protobuf field <code>string EndTime = 4;</code>
     */
    protected $EndTime = '';
    /**
     * 聚合的时间粒度
     *
     * Generated from protobuf field <code>int32 Aggregation = 5;</code>
     */
    protected $Aggregation = 0;
    /**
     * 默认是CDN，支持CDN、ECDN、ALL
     *
     * Generated from protobuf field <code>string BandwidthType = 6;</code>
     */
    protected $BandwidthType = '';
    /**
     * 区域
     *
     * Generated from protobuf field <code>string Area = 7;</code>
     */
    protected $Area = '';
    /**
     * 空间所属区域
     *
     * Generated from protobuf field <code>repeated string RegionList = 8;</code>
     */
    private $RegionList;
    /**
     * 带宽峰值，单位为bps
     *
     * Generated from protobuf field <code>double PeakBandwidth = 9;</code>
     */
    protected $PeakBandwidth = 0.0;
    /**
     * 带宽峰值出现的时间
     *
     * Generated from protobuf field <code>string PeakBandwidthTime = 10;</code>
     */
    protected $PeakBandwidthTime = '';
    /**
     * 带宽95峰值，单位为bps
     *
     * Generated from protobuf field <code>double Peak95Bandwidth = 11;</code>
     */
    protected $Peak95Bandwidth = 0.0;
    /**
     * 带宽95峰值出现的时间
     *
     * Generated from protobuf field <code>string Peak95BandwidthTime = 12;</code>
     */
    protected $Peak95BandwidthTime = '';
    /**
     * 所有时间粒度数据
     *
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodBandwidthData BandwidthDataList = 13;</code>
     */
    private $BandwidthDataList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $DomainList
     *           域名列表
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $DomainInSpaceList
     *           域名列表
     *     @type string $StartTime
     *           查询的起始时间
     *     @type string $EndTime
     *           查询的结束时间
     *     @type int $Aggregation
     *           聚合的时间粒度
     *     @type string $BandwidthType
     *           默认是CDN，支持CDN、ECDN、ALL
     *     @type string $Area
     *           区域
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $RegionList
     *           空间所属区域
     *     @type float $PeakBandwidth
     *           带宽峰值，单位为bps
     *     @type string $PeakBandwidthTime
     *           带宽峰值出现的时间
     *     @type float $Peak95Bandwidth
     *           带宽95峰值，单位为bps
     *     @type string $Peak95BandwidthTime
     *           带宽95峰值出现的时间
     *     @type \Volc\Service\Vod\Models\Business\VodBandwidthData[]|\Google\Protobuf\Internal\RepeatedField $BandwidthDataList
     *           所有时间粒度数据
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * 域名列表
     *
     * Generated from protobuf field <code>repeated string DomainList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDomainList()
    {
        return $this->DomainList;
    }

    /**
     * 域名列表
     *
     * Generated from protobuf field <code>repeated string DomainList = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDomainList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DomainList = $arr;

        return $this;
    }

    /**
     * 域名列表
     *
     * Generated from protobuf field <code>repeated string DomainInSpaceList = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDomainInSpaceList()
    {
        return $this->DomainInSpaceList;
    }

    /**
     * 域名列表
     *
     * Generated from protobuf field <code>repeated string DomainInSpaceList = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDomainInSpaceList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DomainInSpaceList = $arr;

        return $this;
    }

    /**
     * 查询的起始时间
     *
     * Generated from protobuf field <code>string StartTime = 3;</code>
     * @return string
     */
    public function getStartTime()
    {
        return $this->StartTime;
    }

    /**
     * 查询的起始时间
     *
     * Generated from protobuf field <code>string StartTime = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->StartTime = $var;

        return $this;
    }

    /**
     * 查询的结束时间
     *
     * Generated from protobuf field <code>string EndTime = 4;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->EndTime;
    }

    /**
     * 查询的结束时间
     *
     * Generated from protobuf field <code>string EndTime = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->EndTime = $var;

        return $this;
    }

    /**
     * 聚合的时间粒度
     *
     * Generated from protobuf field <code>int32 Aggregation = 5;</code>
     * @return int
     */
    public function getAggregation()
    {
        return $this->Aggregation;
    }

    /**
     * 聚合的时间粒度
     *
     * Generated from protobuf field <code>int32 Aggregation = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAggregation($var)
    {
        GPBUtil::checkInt32($var);
        $this->Aggregation = $var;

        return $this;
    }

    /**
     * 默认是CDN，支持CDN、ECDN、ALL
     *
     * Generated from protobuf field <code>string BandwidthType = 6;</code>
     * @return string
     */
    public function getBandwidthType()
    {
        return $this->BandwidthType;
    }

    /**
     * 默认是CDN，支持CDN、ECDN、ALL
     *
     * Generated from protobuf field <code>string BandwidthType = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBandwidthType($var)
    {
        GPBUtil::checkString($var, True);
        $this->BandwidthType = $var;

        return $this;
    }

    /**
     * 区域
     *
     * Generated from protobuf field <code>string Area = 7;</code>
     * @return string
     */
    public function getArea()
    {
        return $this->Area;
    }

    /**
     * 区域
     *
     * Generated from protobuf field <code>string Area = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setArea($var)
    {
        GPBUtil::checkString($var, True);
        $this->Area = $var;

        return $this;
    }

    /**
     * 空间所属区域
     *
     * Generated from protobuf field <code>repeated string RegionList = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRegionList()
    {
        return $this->RegionList;
    }

    /**
     * 空间所属区域
     *
     * Generated from protobuf field <code>repeated string RegionList = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRegionList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->RegionList = $arr;

        return $this;
    }

    /**
     * 带宽峰值，单位为bps
     *
     * Generated from protobuf field <code>double PeakBandwidth = 9;</code>
     * @return float
     */
    public function getPeakBandwidth()
    {
        return $this->PeakBandwidth;
    }

    /**
     * 带宽峰值，单位为bps
     *
     * Generated from protobuf field <code>double PeakBandwidth = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setPeakBandwidth($var)
    {
        GPBUtil::checkDouble($var);
        $this->PeakBandwidth = $var;

        return $this;
    }

    /**
     * 带宽峰值出现的时间
     *
     * Generated from protobuf field <code>string PeakBandwidthTime = 10;</code>
     * @return string
     */
    public function getPeakBandwidthTime()
    {
        return $this->PeakBandwidthTime;
    }

    /**
     * 带宽峰值出现的时间
     *
     * Generated from protobuf field <code>string PeakBandwidthTime = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setPeakBandwidthTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->PeakBandwidthTime = $var;

        return $this;
    }

    /**
     * 带宽95峰值，单位为bps
     *
     * Generated from protobuf field <code>double Peak95Bandwidth = 11;</code>
     * @return float
     */
    public function getPeak95Bandwidth()
    {
        return $this->Peak95Bandwidth;
    }

    /**
     * 带宽95峰值，单位为bps
     *
     * Generated from protobuf field <code>double Peak95Bandwidth = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setPeak95Bandwidth($var)
    {
        GPBUtil::checkDouble($var);
        $this->Peak95Bandwidth = $var;

        return $this;
    }

    /**
     * 带宽95峰值出现的时间
     *
     * Generated from protobuf field <code>string Peak95BandwidthTime = 12;</code>
     * @return string
     */
    public function getPeak95BandwidthTime()
    {
        return $this->Peak95BandwidthTime;
    }

    /**
     * 带宽95峰值出现的时间
     *
     * Generated from protobuf field <code>string Peak95BandwidthTime = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setPeak95BandwidthTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->Peak95BandwidthTime = $var;

        return $this;
    }

    /**
     * 所有时间粒度数据
     *
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodBandwidthData BandwidthDataList = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBandwidthDataList()
    {
        return $this->BandwidthDataList;
    }

    /**
     * 所有时间粒度数据
     *
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodBandwidthData BandwidthDataList = 13;</code>
     * @param \Volc\Service\Vod\Models\Business\VodBandwidthData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBandwidthDataList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Service\Vod\Models\Business\VodBandwidthData::class);
        $this->BandwidthDataList = $arr;

        return $this;
    }

}

