<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_upload.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodExecutionOperationTaskOcr</code>
 */
class VodExecutionOperationTaskOcr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool WithImageSet = 1;</code>
     */
    protected $WithImageSet = false;
    /**
     * Generated from protobuf field <code>string Mode = 2;</code>
     */
    protected $Mode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $WithImageSet
     *     @type string $Mode
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool WithImageSet = 1;</code>
     * @return bool
     */
    public function getWithImageSet()
    {
        return $this->WithImageSet;
    }

    /**
     * Generated from protobuf field <code>bool WithImageSet = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setWithImageSet($var)
    {
        GPBUtil::checkBool($var);
        $this->WithImageSet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Mode = 2;</code>
     * @return string
     */
    public function getMode()
    {
        return $this->Mode;
    }

    /**
     * Generated from protobuf field <code>string Mode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkString($var, True);
        $this->Mode = $var;

        return $this;
    }

}

