<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_upload.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodExecutionOperationTaskAsr</code>
 */
class VodExecutionOperationTaskAsr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Type = 1;</code>
     */
    protected $Type = '';
    /**
     * Generated from protobuf field <code>string Language = 2;</code>
     */
    protected $Language = '';
    /**
     * Generated from protobuf field <code>string WithSpeakerInfo = 3;</code>
     */
    protected $WithSpeakerInfo = '';
    /**
     * Generated from protobuf field <code>string WithConfidence = 4;</code>
     */
    protected $WithConfidence = '';
    /**
     * Generated from protobuf field <code>string Mode = 5;</code>
     */
    protected $Mode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Type
     *     @type string $Language
     *     @type string $WithSpeakerInfo
     *     @type string $WithConfidence
     *     @type string $Mode
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>string Type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Language = 2;</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->Language;
    }

    /**
     * Generated from protobuf field <code>string Language = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string WithSpeakerInfo = 3;</code>
     * @return string
     */
    public function getWithSpeakerInfo()
    {
        return $this->WithSpeakerInfo;
    }

    /**
     * Generated from protobuf field <code>string WithSpeakerInfo = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setWithSpeakerInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->WithSpeakerInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string WithConfidence = 4;</code>
     * @return string
     */
    public function getWithConfidence()
    {
        return $this->WithConfidence;
    }

    /**
     * Generated from protobuf field <code>string WithConfidence = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setWithConfidence($var)
    {
        GPBUtil::checkString($var, True);
        $this->WithConfidence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Mode = 5;</code>
     * @return string
     */
    public function getMode()
    {
        return $this->Mode;
    }

    /**
     * Generated from protobuf field <code>string Mode = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkString($var, True);
        $this->Mode = $var;

        return $this;
    }

}

