<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_upload.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodExecutionOperationTask</code>
 */
class VodExecutionOperationTask extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Type = 1;</code>
     */
    protected $Type = '';
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodExecutionOperationTaskOcr Ocr = 2;</code>
     */
    protected $Ocr = null;
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodExecutionOperationTaskAsr Asr = 3;</code>
     */
    protected $Asr = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Type
     *     @type \Volc\Service\Vod\Models\Business\VodExecutionOperationTaskOcr $Ocr
     *     @type \Volc\Service\Vod\Models\Business\VodExecutionOperationTaskAsr $Asr
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>string Type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodExecutionOperationTaskOcr Ocr = 2;</code>
     * @return \Volc\Service\Vod\Models\Business\VodExecutionOperationTaskOcr|null
     */
    public function getOcr()
    {
        return $this->Ocr;
    }

    public function hasOcr()
    {
        return isset($this->Ocr);
    }

    public function clearOcr()
    {
        unset($this->Ocr);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodExecutionOperationTaskOcr Ocr = 2;</code>
     * @param \Volc\Service\Vod\Models\Business\VodExecutionOperationTaskOcr $var
     * @return $this
     */
    public function setOcr($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\VodExecutionOperationTaskOcr::class);
        $this->Ocr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodExecutionOperationTaskAsr Asr = 3;</code>
     * @return \Volc\Service\Vod\Models\Business\VodExecutionOperationTaskAsr|null
     */
    public function getAsr()
    {
        return $this->Asr;
    }

    public function hasAsr()
    {
        return isset($this->Asr);
    }

    public function clearAsr()
    {
        unset($this->Asr);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodExecutionOperationTaskAsr Asr = 3;</code>
     * @param \Volc\Service\Vod\Models\Business\VodExecutionOperationTaskAsr $var
     * @return $this
     */
    public function setAsr($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\VodExecutionOperationTaskAsr::class);
        $this->Asr = $var;

        return $this;
    }

}

