<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_media.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodGetFileInfosData</code>
 */
class VodGetFileInfosData extends \Google\Protobuf\Internal\Message
{
    /**
     *文件信息
     *
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodFileInfo FileInfos = 1;</code>
     */
    private $FileInfos;
    /**
     *不存在的文件
     *
     * Generated from protobuf field <code>repeated string NotExistFileNames = 2;</code>
     */
    private $NotExistFileNames;
    /**
     *不存在的文件(URL编码格式)
     *
     * Generated from protobuf field <code>repeated string NotExistEncodedFileNames = 3;</code>
     */
    private $NotExistEncodedFileNames;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Volc\Service\Vod\Models\Business\VodFileInfo[]|\Google\Protobuf\Internal\RepeatedField $FileInfos
     *          文件信息
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $NotExistFileNames
     *          不存在的文件
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $NotExistEncodedFileNames
     *          不存在的文件(URL编码格式)
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodMedia::initOnce();
        parent::__construct($data);
    }

    /**
     *文件信息
     *
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodFileInfo FileInfos = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFileInfos()
    {
        return $this->FileInfos;
    }

    /**
     *文件信息
     *
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodFileInfo FileInfos = 1;</code>
     * @param \Volc\Service\Vod\Models\Business\VodFileInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFileInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Service\Vod\Models\Business\VodFileInfo::class);
        $this->FileInfos = $arr;

        return $this;
    }

    /**
     *不存在的文件
     *
     * Generated from protobuf field <code>repeated string NotExistFileNames = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotExistFileNames()
    {
        return $this->NotExistFileNames;
    }

    /**
     *不存在的文件
     *
     * Generated from protobuf field <code>repeated string NotExistFileNames = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotExistFileNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->NotExistFileNames = $arr;

        return $this;
    }

    /**
     *不存在的文件(URL编码格式)
     *
     * Generated from protobuf field <code>repeated string NotExistEncodedFileNames = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotExistEncodedFileNames()
    {
        return $this->NotExistEncodedFileNames;
    }

    /**
     *不存在的文件(URL编码格式)
     *
     * Generated from protobuf field <code>repeated string NotExistEncodedFileNames = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotExistEncodedFileNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->NotExistEncodedFileNames = $arr;

        return $this;
    }

}

