<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_media.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodGetAdAuditResultByVidData</code>
 */
class VodGetAdAuditResultByVidData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodAuditInfo VodAuditInfos = 1;</code>
     */
    private $VodAuditInfos;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Volc\Service\Vod\Models\Business\VodAuditInfo[]|\Google\Protobuf\Internal\RepeatedField $VodAuditInfos
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodMedia::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodAuditInfo VodAuditInfos = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVodAuditInfos()
    {
        return $this->VodAuditInfos;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodAuditInfo VodAuditInfos = 1;</code>
     * @param \Volc\Service\Vod\Models\Business\VodAuditInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVodAuditInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Service\Vod\Models\Business\VodAuditInfo::class);
        $this->VodAuditInfos = $arr;

        return $this;
    }

}

