<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_workflow.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodListWatermarkResponseResult</code>
 */
class VodListWatermarkResponseResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Limit = 1;</code>
     */
    protected $Limit = 0;
    /**
     * Generated from protobuf field <code>int32 Offset = 2;</code>
     */
    protected $Offset = 0;
    /**
     * Generated from protobuf field <code>int64 Total = 3;</code>
     */
    protected $Total = 0;
    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.LogoTemplate Data = 4;</code>
     */
    private $Data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Limit
     *     @type int $Offset
     *     @type int|string $Total
     *     @type \Volc\Service\Vod\Models\Business\LogoTemplate[]|\Google\Protobuf\Internal\RepeatedField $Data
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodWorkflow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 Limit = 1;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->Limit;
    }

    /**
     * Generated from protobuf field <code>int32 Limit = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->Limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Offset = 2;</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->Offset;
    }

    /**
     * Generated from protobuf field <code>int32 Offset = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->Offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Total = 3;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->Total;
    }

    /**
     * Generated from protobuf field <code>int64 Total = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt64($var);
        $this->Total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.LogoTemplate Data = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->Data;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.LogoTemplate Data = 4;</code>
     * @param \Volc\Service\Vod\Models\Business\LogoTemplate[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Service\Vod\Models\Business\LogoTemplate::class);
        $this->Data = $arr;

        return $this;
    }

}

