<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod/business/vod_media.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodMediaPosterUrlInfo</code>
 */
class VodMediaPosterUrlInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string PosterUri = 1;</code>
     */
    protected $PosterUri = '';
    /**
     * Generated from protobuf field <code>string PosterUrl = 2;</code>
     */
    protected $PosterUrl = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $PosterUri
     *     @type string $PosterUrl
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodMedia::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string PosterUri = 1;</code>
     * @return string
     */
    public function getPosterUri()
    {
        return $this->PosterUri;
    }

    /**
     * Generated from protobuf field <code>string PosterUri = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPosterUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->PosterUri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string PosterUrl = 2;</code>
     * @return string
     */
    public function getPosterUrl()
    {
        return $this->PosterUrl;
    }

    /**
     * Generated from protobuf field <code>string PosterUrl = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPosterUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->PosterUrl = $var;

        return $this;
    }

}

