<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_cdn.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodOriginArgAction</code>
 */
class VodOriginArgAction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodOriginArgComponents OriginArgComponents = 1;</code>
     */
    private $OriginArgComponents;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Volc\Service\Vod\Models\Business\VodOriginArgComponents[]|\Google\Protobuf\Internal\RepeatedField $OriginArgComponents
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodOriginArgComponents OriginArgComponents = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOriginArgComponents()
    {
        return $this->OriginArgComponents;
    }

    /**
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.VodOriginArgComponents OriginArgComponents = 1;</code>
     * @param \Volc\Service\Vod\Models\Business\VodOriginArgComponents[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOriginArgComponents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Service\Vod\Models\Business\VodOriginArgComponents::class);
        $this->OriginArgComponents = $arr;

        return $this;
    }

}

