<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_cdn.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodOriginalConfig</code>
 */
class VodOriginalConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * 源站地址
     *
     * Generated from protobuf field <code>string Origins = 1;</code>
     */
    protected $Origins = '';
    /**
     * 源站类型
     *
     * Generated from protobuf field <code>string OriginType = 2;</code>
     */
    protected $OriginType = '';
    /**
     * 源站地址类型
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodDomainSourceStationAddressType SourceStationAddressType = 3;</code>
     */
    protected $SourceStationAddressType = 0;
    /**
     * 回源Host
     *
     * Generated from protobuf field <code>string Host = 4;</code>
     */
    protected $Host = '';
    /**
     * 是否私有存储桶
     *
     * Generated from protobuf field <code>bool PrivateBucketAccess = 5;</code>
     */
    protected $PrivateBucketAccess = false;
    /**
     * 私有存储桶鉴权
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodPrivateBucketAuth PrivateBucketAuth = 6;</code>
     */
    protected $PrivateBucketAuth = null;
    /**
     * 回源桶地址
     *
     * Generated from protobuf field <code>string Region = 7;</code>
     */
    protected $Region = '';
    /**
     * Generated from protobuf field <code>string HttpPort = 8;</code>
     */
    protected $HttpPort = '';
    /**
     * Generated from protobuf field <code>string HttpsPort = 9;</code>
     */
    protected $HttpsPort = '';
    /**
     * Generated from protobuf field <code>string Weight = 10;</code>
     */
    protected $Weight = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Origins
     *           源站地址
     *     @type string $OriginType
     *           源站类型
     *     @type int $SourceStationAddressType
     *           源站地址类型
     *     @type string $Host
     *           回源Host
     *     @type bool $PrivateBucketAccess
     *           是否私有存储桶
     *     @type \Volc\Service\Vod\Models\Business\VodPrivateBucketAuth $PrivateBucketAuth
     *           私有存储桶鉴权
     *     @type string $Region
     *           回源桶地址
     *     @type string $HttpPort
     *     @type string $HttpsPort
     *     @type string $Weight
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodCdn::initOnce();
        parent::__construct($data);
    }

    /**
     * 源站地址
     *
     * Generated from protobuf field <code>string Origins = 1;</code>
     * @return string
     */
    public function getOrigins()
    {
        return $this->Origins;
    }

    /**
     * 源站地址
     *
     * Generated from protobuf field <code>string Origins = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrigins($var)
    {
        GPBUtil::checkString($var, True);
        $this->Origins = $var;

        return $this;
    }

    /**
     * 源站类型
     *
     * Generated from protobuf field <code>string OriginType = 2;</code>
     * @return string
     */
    public function getOriginType()
    {
        return $this->OriginType;
    }

    /**
     * 源站类型
     *
     * Generated from protobuf field <code>string OriginType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginType($var)
    {
        GPBUtil::checkString($var, True);
        $this->OriginType = $var;

        return $this;
    }

    /**
     * 源站地址类型
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodDomainSourceStationAddressType SourceStationAddressType = 3;</code>
     * @return int
     */
    public function getSourceStationAddressType()
    {
        return $this->SourceStationAddressType;
    }

    /**
     * 源站地址类型
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodDomainSourceStationAddressType SourceStationAddressType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSourceStationAddressType($var)
    {
        GPBUtil::checkEnum($var, \Volc\Service\Vod\Models\Business\VodDomainSourceStationAddressType::class);
        $this->SourceStationAddressType = $var;

        return $this;
    }

    /**
     * 回源Host
     *
     * Generated from protobuf field <code>string Host = 4;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->Host;
    }

    /**
     * 回源Host
     *
     * Generated from protobuf field <code>string Host = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->Host = $var;

        return $this;
    }

    /**
     * 是否私有存储桶
     *
     * Generated from protobuf field <code>bool PrivateBucketAccess = 5;</code>
     * @return bool
     */
    public function getPrivateBucketAccess()
    {
        return $this->PrivateBucketAccess;
    }

    /**
     * 是否私有存储桶
     *
     * Generated from protobuf field <code>bool PrivateBucketAccess = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setPrivateBucketAccess($var)
    {
        GPBUtil::checkBool($var);
        $this->PrivateBucketAccess = $var;

        return $this;
    }

    /**
     * 私有存储桶鉴权
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodPrivateBucketAuth PrivateBucketAuth = 6;</code>
     * @return \Volc\Service\Vod\Models\Business\VodPrivateBucketAuth|null
     */
    public function getPrivateBucketAuth()
    {
        return $this->PrivateBucketAuth;
    }

    public function hasPrivateBucketAuth()
    {
        return isset($this->PrivateBucketAuth);
    }

    public function clearPrivateBucketAuth()
    {
        unset($this->PrivateBucketAuth);
    }

    /**
     * 私有存储桶鉴权
     *
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodPrivateBucketAuth PrivateBucketAuth = 6;</code>
     * @param \Volc\Service\Vod\Models\Business\VodPrivateBucketAuth $var
     * @return $this
     */
    public function setPrivateBucketAuth($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\VodPrivateBucketAuth::class);
        $this->PrivateBucketAuth = $var;

        return $this;
    }

    /**
     * 回源桶地址
     *
     * Generated from protobuf field <code>string Region = 7;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->Region;
    }

    /**
     * 回源桶地址
     *
     * Generated from protobuf field <code>string Region = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->Region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string HttpPort = 8;</code>
     * @return string
     */
    public function getHttpPort()
    {
        return $this->HttpPort;
    }

    /**
     * Generated from protobuf field <code>string HttpPort = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setHttpPort($var)
    {
        GPBUtil::checkString($var, True);
        $this->HttpPort = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string HttpsPort = 9;</code>
     * @return string
     */
    public function getHttpsPort()
    {
        return $this->HttpsPort;
    }

    /**
     * Generated from protobuf field <code>string HttpsPort = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setHttpsPort($var)
    {
        GPBUtil::checkString($var, True);
        $this->HttpsPort = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Weight = 10;</code>
     * @return string
     */
    public function getWeight()
    {
        return $this->Weight;
    }

    /**
     * Generated from protobuf field <code>string Weight = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkString($var, True);
        $this->Weight = $var;

        return $this;
    }

}

