<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_project.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodProjectInfo</code>
 */
class VodProjectInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * 项目名称
     *
     * Generated from protobuf field <code>string ProjectName = 1;</code>
     */
    protected $ProjectName = '';
    /**
     * 项目展示名称
     *
     * Generated from protobuf field <code>string DisplayName = 2;</code>
     */
    protected $DisplayName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ProjectName
     *           项目名称
     *     @type string $DisplayName
     *           项目展示名称
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodProject::initOnce();
        parent::__construct($data);
    }

    /**
     * 项目名称
     *
     * Generated from protobuf field <code>string ProjectName = 1;</code>
     * @return string
     */
    public function getProjectName()
    {
        return $this->ProjectName;
    }

    /**
     * 项目名称
     *
     * Generated from protobuf field <code>string ProjectName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProjectName($var)
    {
        GPBUtil::checkString($var, True);
        $this->ProjectName = $var;

        return $this;
    }

    /**
     * 项目展示名称
     *
     * Generated from protobuf field <code>string DisplayName = 2;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->DisplayName;
    }

    /**
     * 项目展示名称
     *
     * Generated from protobuf field <code>string DisplayName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->DisplayName = $var;

        return $this;
    }

}

