<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_media.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodSubmitUnblockMediaTaskResult</code>
 */
class VodSubmitUnblockMediaTaskResult extends \Google\Protobuf\Internal\Message
{
    /**
     * 不存在的Vid列表
     *
     * Generated from protobuf field <code>repeated string NotExistVids = 1;</code>
     */
    private $NotExistVids;
    /**
     * 已封禁的Vid列表
     *
     * Generated from protobuf field <code>repeated string UnblockedVids = 2;</code>
     */
    private $UnblockedVids;
    /**
     * 解封中的Vid列表
     *
     * Generated from protobuf field <code>repeated string BlockingVids = 3;</code>
     */
    private $BlockingVids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $NotExistVids
     *           不存在的Vid列表
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $UnblockedVids
     *           已封禁的Vid列表
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $BlockingVids
     *           解封中的Vid列表
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodMedia::initOnce();
        parent::__construct($data);
    }

    /**
     * 不存在的Vid列表
     *
     * Generated from protobuf field <code>repeated string NotExistVids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotExistVids()
    {
        return $this->NotExistVids;
    }

    /**
     * 不存在的Vid列表
     *
     * Generated from protobuf field <code>repeated string NotExistVids = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotExistVids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->NotExistVids = $arr;

        return $this;
    }

    /**
     * 已封禁的Vid列表
     *
     * Generated from protobuf field <code>repeated string UnblockedVids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnblockedVids()
    {
        return $this->UnblockedVids;
    }

    /**
     * 已封禁的Vid列表
     *
     * Generated from protobuf field <code>repeated string UnblockedVids = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnblockedVids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->UnblockedVids = $arr;

        return $this;
    }

    /**
     * 解封中的Vid列表
     *
     * Generated from protobuf field <code>repeated string BlockingVids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBlockingVids()
    {
        return $this->BlockingVids;
    }

    /**
     * 解封中的Vid列表
     *
     * Generated from protobuf field <code>repeated string BlockingVids = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBlockingVids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->BlockingVids = $arr;

        return $this;
    }

}

