<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_upload.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.VodUploadTemplate</code>
 */
class VodUploadTemplate extends \Google\Protobuf\Internal\Message
{
    /**
     * 工作流模板id 
     *
     * Generated from protobuf field <code>repeated string TemplateIds = 1;</code>
     */
    private $TemplateIds;
    /**
     * 工作流模板类型，imp: 智能处理，transcode: 点播转码 
     *
     * Generated from protobuf field <code>string TemplateType = 2;</code>
     */
    protected $TemplateType = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $TemplateIds
     *           工作流模板id 
     *     @type string $TemplateType
     *           工作流模板类型，imp: 智能处理，transcode: 点播转码 
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * 工作流模板id 
     *
     * Generated from protobuf field <code>repeated string TemplateIds = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTemplateIds()
    {
        return $this->TemplateIds;
    }

    /**
     * 工作流模板id 
     *
     * Generated from protobuf field <code>repeated string TemplateIds = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTemplateIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->TemplateIds = $arr;

        return $this;
    }

    /**
     * 工作流模板类型，imp: 智能处理，transcode: 点播转码 
     *
     * Generated from protobuf field <code>string TemplateType = 2;</code>
     * @return string
     */
    public function getTemplateType()
    {
        return $this->TemplateType;
    }

    /**
     * 工作流模板类型，imp: 智能处理，transcode: 点播转码 
     *
     * Generated from protobuf field <code>string TemplateType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTemplateType($var)
    {
        GPBUtil::checkString($var, True);
        $this->TemplateType = $var;

        return $this;
    }

}

