<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_workflow.proto

namespace Volc\Service\Vod\Models\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Business.WorkflowTemplate</code>
 */
class WorkflowTemplate extends \Google\Protobuf\Internal\Message
{
    /**
     * 模板Id
     *
     * Generated from protobuf field <code>string TemplateId = 1;</code>
     */
    protected $TemplateId = '';
    /**
     * 空间名
     *
     * Generated from protobuf field <code>string SpaceName = 2;</code>
     */
    protected $SpaceName = '';
    /**
     * 模板名称
     *
     * Generated from protobuf field <code>string Name = 3;</code>
     */
    protected $Name = '';
    /**
     * 模板描述
     *
     * Generated from protobuf field <code>string Description = 4;</code>
     */
    protected $Description = '';
    /**
     * 多个值通过 ',' 连接
     *
     * Generated from protobuf field <code>string Type = 6;</code>
     */
    protected $Type = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp CreatedAt = 12;</code>
     */
    protected $CreatedAt = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp UpdatedAt = 13;</code>
     */
    protected $UpdatedAt = null;
    /**
     * 模板版本
     *
     * Generated from protobuf field <code>string CommitId = 14;</code>
     */
    protected $CommitId = '';
    /**
     * 任务集合
     *
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.Activity Activities = 19;</code>
     */
    private $Activities;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $TemplateId
     *           模板Id
     *     @type string $SpaceName
     *           空间名
     *     @type string $Name
     *           模板名称
     *     @type string $Description
     *           模板描述
     *     @type string $Type
     *           多个值通过 ',' 连接
     *     @type \Google\Protobuf\Timestamp $CreatedAt
     *     @type \Google\Protobuf\Timestamp $UpdatedAt
     *     @type string $CommitId
     *           模板版本
     *     @type \Volc\Service\Vod\Models\Business\Activity[]|\Google\Protobuf\Internal\RepeatedField $Activities
     *           任务集合
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\VodWorkflow::initOnce();
        parent::__construct($data);
    }

    /**
     * 模板Id
     *
     * Generated from protobuf field <code>string TemplateId = 1;</code>
     * @return string
     */
    public function getTemplateId()
    {
        return $this->TemplateId;
    }

    /**
     * 模板Id
     *
     * Generated from protobuf field <code>string TemplateId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTemplateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->TemplateId = $var;

        return $this;
    }

    /**
     * 空间名
     *
     * Generated from protobuf field <code>string SpaceName = 2;</code>
     * @return string
     */
    public function getSpaceName()
    {
        return $this->SpaceName;
    }

    /**
     * 空间名
     *
     * Generated from protobuf field <code>string SpaceName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSpaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SpaceName = $var;

        return $this;
    }

    /**
     * 模板名称
     *
     * Generated from protobuf field <code>string Name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * 模板名称
     *
     * Generated from protobuf field <code>string Name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * 模板描述
     *
     * Generated from protobuf field <code>string Description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->Description;
    }

    /**
     * 模板描述
     *
     * Generated from protobuf field <code>string Description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->Description = $var;

        return $this;
    }

    /**
     * 多个值通过 ',' 连接
     *
     * Generated from protobuf field <code>string Type = 6;</code>
     * @return string
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * 多个值通过 ',' 连接
     *
     * Generated from protobuf field <code>string Type = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp CreatedAt = 12;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->CreatedAt;
    }

    public function hasCreatedAt()
    {
        return isset($this->CreatedAt);
    }

    public function clearCreatedAt()
    {
        unset($this->CreatedAt);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp CreatedAt = 12;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->CreatedAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp UpdatedAt = 13;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->UpdatedAt;
    }

    public function hasUpdatedAt()
    {
        return isset($this->UpdatedAt);
    }

    public function clearUpdatedAt()
    {
        unset($this->UpdatedAt);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp UpdatedAt = 13;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->UpdatedAt = $var;

        return $this;
    }

    /**
     * 模板版本
     *
     * Generated from protobuf field <code>string CommitId = 14;</code>
     * @return string
     */
    public function getCommitId()
    {
        return $this->CommitId;
    }

    /**
     * 模板版本
     *
     * Generated from protobuf field <code>string CommitId = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setCommitId($var)
    {
        GPBUtil::checkString($var, True);
        $this->CommitId = $var;

        return $this;
    }

    /**
     * 任务集合
     *
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.Activity Activities = 19;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActivities()
    {
        return $this->Activities;
    }

    /**
     * 任务集合
     *
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.Activity Activities = 19;</code>
     * @param \Volc\Service\Vod\Models\Business\Activity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActivities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Service\Vod\Models\Business\Activity::class);
        $this->Activities = $arr;

        return $this;
    }

}

