// Code generated by protoc-gen-volcengine-sdk
// source: updateUploadSpaceConfig
// DO NOT EDIT!
<?php
require('../../vendor/autoload.php');

// Create a VOD instance in the specified region.
// $client = Volc\Service\Vod\Vod::getInstance('cn-north-1');
$client = Volc\Service\Vod\Vod::getInstance();

// Configure your Access Key ID (AK) and Secret Access Key (SK) in the environment variables or in the local ~/.volc/config file. For detailed instructions, see https://www.volcengine.com/docs/4/4408.
// The SDK will automatically fetch the AK and SK from the environment variables or the ~/.volc/config file as needed.
// During testing, you may use the following code snippet. However, do not store the AK and SK directly in your project code to prevent potential leakage and safeguard the security of all resources associated with your account.
// $client->setAccessKey('your ak');
// $client->setSecretKey('your sk');

$request = new Volc\Service\Vod\Models\Request\VodUpdateUploadSpaceConfigRequest();
$request->setSpaceName("your SpaceName");
$request->setAutoPoster("your AutoPoster");
$request->setCustomPosterConfig(new Volc\Service\Vod\Models\Business\CustomPosterConfig());
$request->setGetPosterMode("your GetPosterMode");
$request->setAutoPosterCandidate("your AutoPosterCandidate");
$request->setAutoTranscode("your AutoTranscode");
$request->setTranscodeConfig(new Volc\Service\Vod\Models\Business\TranscodeConfig());
$request->setAutoSetVideoStatus("your AutoSetVideoStatus");
$request->setUploadOverwrite("your UploadOverwrite");
$request->setCallbackReturnPlayUrl("your CallbackReturnPlayUrl");
$request->setCallbackReturnRunId("your CallbackReturnRunId");
$request->setGetMetaMode("your GetMetaMode");
$request->setAutoGetArchiveVideoMeta("your AutoGetArchiveVideoMeta");
$request->setAutoGetIAVideoMeta("your AutoGetIAVideoMeta");
$request->setMetaGetMd5("your MetaGetMd5");


$response = new Volc\Service\Vod\Models\Response\VodUpdateUploadSpaceConfigResponse();
try {
    $response = $client->updateUploadSpaceConfig($request);
} catch (Exception $e) {
    echo $e, "\n";
} catch (Throwable $e) {
    echo $e, "\n";
}
if ($response != null && $response->getResponseMetadata() != null && $response->getResponseMetadata()->getError() != null) {
    echo $response->getResponseMetadata()->getError()->serializeToJsonString(), "\n";
} else {
    echo $response->serializeToJsonString(), "\n";
}
