// Code generated by protoc-gen-volcengine-sdk
// source: updateDomainUrlAuthConfig
// DO NOT EDIT!
<?php
require('../../vendor/autoload.php');

$client = Volc\Service\Vod\Vod::getInstance();
$client->setAccessKey('your ak');
$client->setSecretKey('your sk');

$request = new Volc\Service\Vod\Models\Request\VodUpdateDomainUrlAuthConfigV2Request();
$request->setSpaceName("your SpaceName");
$request->setDomainType("your DomainType");
$request->setDomain("your Domain");
$request->setMainKey("your MainKey");
$request->setBackupKey("your BackupKey");
$request->setStatus("your Status");


$response = new Volc\Service\Vod\Models\Response\VodUpdateDomainUrlAuthConfigV2Response();
try {
    $response = $client->updateDomainUrlAuthConfig($request);
} catch (Exception $e) {
    echo $e, "\n";
} catch (Throwable $e) {
    echo $e, "\n";
}
if ($response != null && $response->getResponseMetadata() != null && $response->getResponseMetadata()->getError() != null) {
    echo $response->getResponseMetadata()->getError()->serializeToJsonString(), "\n";
} else {
    echo $response->serializeToJsonString(), "\n";
}
