// Code generated by protoc-gen-volcengine-sdk
// source: describeVodSpaceWorkflowDetailData
// DO NOT EDIT!
<?php
require('../../vendor/autoload.php');

$client = Volc\Service\Vod\Vod::getInstance();
$client->setAccessKey('your ak');
$client->setSecretKey('your sk');

$request = new Volc\Service\Vod\Models\Request\DescribeVodSpaceWorkflowDetailDataRequest();
$request->setRegion("your Region");
$request->setSpace("your Space");
$request->setStartTime("your StartTime");
$request->setEndTime("your EndTime");
$request->setPageSize(0);
$request->setPageNum(0);


$response = new Volc\Service\Vod\Models\Response\DescribeVodSpaceWorkflowDetailDataResponse();
try {
    $response = $client->describeVodSpaceWorkflowDetailData($request);
} catch (Exception $e) {
    echo $e, "\n";
} catch (Throwable $e) {
    echo $e, "\n";
}
if ($response != null && $response->getResponseMetadata() != null && $response->getResponseMetadata()->getError() != null) {
    echo $response->getResponseMetadata()->getError()->serializeToJsonString(), "\n";
} else {
    echo $response->serializeToJsonString(), "\n";
}
