// Code generated by protoc-gen-volcengine-sdk
// source: generatePushURL
// DO NOT EDIT!
<?php

use Volc\Service\Live\Models\Response\GeneratePushURLResponse;

require('../../vendor/autoload.php');

$client = Volc\Service\Live\Live::getInstance();

$client->setAccessKey('');
$client->setSecretKey('');

$request = new Volc\Service\Live\Models\Request\GeneratePushURLRequest();
$request->setVhost("");
$request->setDomain("");
$request->setApp("");
$request->setStream("");
$request->setExpiredTime("");

$response = new GeneratePushURLResponse();


try {
    $response = $client->generatePushURL($request);
} catch (Exception $e) {
    echo $e, "\n";
} catch (Throwable $e) {
    echo $e, "\n";
}
if ($response != null && $response->getResponseMetadata() != null && $response->getResponseMetadata()->getError() != null) {
    echo $response->getResponseMetadata()->getError()->serializeToJsonString(), "\n";
} else {
    echo $response->serializeToJsonString(), "\n";
}
