<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod/business/vod_upload.proto

namespace Volc\Models\Vod\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Models.Vod.Business.VodApplyUploadInfoData</code>
 */
class VodApplyUploadInfoData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Volcengine.Models.Vod.Business.VodUploadAddress UploadAddress = 1;</code>
     */
    protected $UploadAddress = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Volc\Models\Vod\Business\VodUploadAddress $UploadAddress
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Models\Vod\GPBMetadata\VodUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Models.Vod.Business.VodUploadAddress UploadAddress = 1;</code>
     * @return \Volc\Models\Vod\Business\VodUploadAddress
     */
    public function getUploadAddress()
    {
        return $this->UploadAddress;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Models.Vod.Business.VodUploadAddress UploadAddress = 1;</code>
     * @param \Volc\Models\Vod\Business\VodUploadAddress $var
     * @return $this
     */
    public function setUploadAddress($var)
    {
        GPBUtil::checkMessage($var, \Volc\Models\Vod\Business\VodUploadAddress::class);
        $this->UploadAddress = $var;

        return $this;
    }

}

