<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod/business/vod_media.proto

namespace Volc\Models\Vod\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Models.Vod.Business.VodMediaInfo</code>
 */
class VodMediaInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *视频基础信息
     *
     * Generated from protobuf field <code>.Volcengine.Models.Vod.Business.VodMediaBasicInfo BasicInfo = 1;</code>
     */
    protected $BasicInfo = null;
    /**
     *原视频信息
     *
     * Generated from protobuf field <code>.Volcengine.Models.Vod.Business.VodSourceInfo SourceInfo = 2;</code>
     */
    protected $SourceInfo = null;
    /**
     *转码视频信息列表
     *
     * Generated from protobuf field <code>repeated .Volcengine.Models.Vod.Business.VodTranscodeInfo TranscodeInfos = 3;</code>
     */
    private $TranscodeInfos;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Volc\Models\Vod\Business\VodMediaBasicInfo $BasicInfo
     *          视频基础信息
     *     @type \Volc\Models\Vod\Business\VodSourceInfo $SourceInfo
     *          原视频信息
     *     @type \Volc\Models\Vod\Business\VodTranscodeInfo[]|\Google\Protobuf\Internal\RepeatedField $TranscodeInfos
     *          转码视频信息列表
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Models\Vod\GPBMetadata\VodMedia::initOnce();
        parent::__construct($data);
    }

    /**
     *视频基础信息
     *
     * Generated from protobuf field <code>.Volcengine.Models.Vod.Business.VodMediaBasicInfo BasicInfo = 1;</code>
     * @return \Volc\Models\Vod\Business\VodMediaBasicInfo
     */
    public function getBasicInfo()
    {
        return $this->BasicInfo;
    }

    /**
     *视频基础信息
     *
     * Generated from protobuf field <code>.Volcengine.Models.Vod.Business.VodMediaBasicInfo BasicInfo = 1;</code>
     * @param \Volc\Models\Vod\Business\VodMediaBasicInfo $var
     * @return $this
     */
    public function setBasicInfo($var)
    {
        GPBUtil::checkMessage($var, \Volc\Models\Vod\Business\VodMediaBasicInfo::class);
        $this->BasicInfo = $var;

        return $this;
    }

    /**
     *原视频信息
     *
     * Generated from protobuf field <code>.Volcengine.Models.Vod.Business.VodSourceInfo SourceInfo = 2;</code>
     * @return \Volc\Models\Vod\Business\VodSourceInfo
     */
    public function getSourceInfo()
    {
        return $this->SourceInfo;
    }

    /**
     *原视频信息
     *
     * Generated from protobuf field <code>.Volcengine.Models.Vod.Business.VodSourceInfo SourceInfo = 2;</code>
     * @param \Volc\Models\Vod\Business\VodSourceInfo $var
     * @return $this
     */
    public function setSourceInfo($var)
    {
        GPBUtil::checkMessage($var, \Volc\Models\Vod\Business\VodSourceInfo::class);
        $this->SourceInfo = $var;

        return $this;
    }

    /**
     *转码视频信息列表
     *
     * Generated from protobuf field <code>repeated .Volcengine.Models.Vod.Business.VodTranscodeInfo TranscodeInfos = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTranscodeInfos()
    {
        return $this->TranscodeInfos;
    }

    /**
     *转码视频信息列表
     *
     * Generated from protobuf field <code>repeated .Volcengine.Models.Vod.Business.VodTranscodeInfo TranscodeInfos = 3;</code>
     * @param \Volc\Models\Vod\Business\VodTranscodeInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTranscodeInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Models\Vod\Business\VodTranscodeInfo::class);
        $this->TranscodeInfos = $arr;

        return $this;
    }

}

