<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod/business/vod_common.proto

namespace Volc\Models\Vod\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Models.Vod.Business.VodPlayInfo</code>
 */
class VodPlayInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *文件ID
     *
     * Generated from protobuf field <code>string FileId = 1;</code>
     */
    protected $FileId = '';
    /**
     * hash值
     *
     * Generated from protobuf field <code>string Md5 = 2;</code>
     */
    protected $Md5 = '';
    /**
     * 文件类型 video/audio
     *
     * Generated from protobuf field <code>string FileType = 3;</code>
     */
    protected $FileType = '';
    /**
     *视频格式
     *
     * Generated from protobuf field <code>string Format = 4;</code>
     */
    protected $Format = '';
    /**
     *编码类型
     *
     * Generated from protobuf field <code>string Codec = 5;</code>
     */
    protected $Codec = '';
    /**
     *视频分辨率
     *
     * Generated from protobuf field <code>string Definition = 6;</code>
     */
    protected $Definition = '';
    /**
     *主播放地址
     *
     * Generated from protobuf field <code>string MainPlayUrl = 7;</code>
     */
    protected $MainPlayUrl = '';
    /**
     *备用播放地址
     *
     * Generated from protobuf field <code>string BackupPlayUrl = 8;</code>
     */
    protected $BackupPlayUrl = '';
    /**
     *码率(Kbps)
     *
     * Generated from protobuf field <code>float Bitrate = 9;</code>
     */
    protected $Bitrate = 0.0;
    /**
     *视频高度
     *
     * Generated from protobuf field <code>int64 Width = 10;</code>
     */
    protected $Width = 0;
    /**
     *视频宽度
     *
     * Generated from protobuf field <code>int64 Height = 11;</code>
     */
    protected $Height = 0;
    /**
     *文件大小
     *
     * Generated from protobuf field <code>int64 Size = 12;</code>
     */
    protected $Size = 0;
    /**
     *劫持校验信息
     *
     * Generated from protobuf field <code>string CheckInfo = 13;</code>
     */
    protected $CheckInfo = '';
    /**
     * dash segment_base 分片信息
     *
     * Generated from protobuf field <code>string IndexRange = 14;</code>
     */
    protected $IndexRange = '';
    /**
     * dash segment_base 分片信息
     *
     * Generated from protobuf field <code>string InitRange = 15;</code>
     */
    protected $InitRange = '';
    /**
     *预加载大小
     *
     * Generated from protobuf field <code>int64 PreloadSize = 16;</code>
     */
    protected $PreloadSize = 0;
    /**
     *最小步长
     *
     * Generated from protobuf field <code>int64 PreloadMinStep = 17;</code>
     */
    protected $PreloadMinStep = 0;
    /**
     *最大步长
     *
     * Generated from protobuf field <code>int64 PreloadMaxStep = 18;</code>
     */
    protected $PreloadMaxStep = 0;
    /**
     *间隔,提前加载时长
     *
     * Generated from protobuf field <code>int64 PreloadInterval = 19;</code>
     */
    protected $PreloadInterval = 0;
    /**
     * p2p点播时，校验文件地址
     *
     * Generated from protobuf field <code>string P2pVerifyUrl = 20;</code>
     */
    protected $P2pVerifyUrl = '';
    /**
     *加密过的秘钥
     *
     * Generated from protobuf field <code>string PlayAuth = 21;</code>
     */
    protected $PlayAuth = '';
    /**
     *密钥keyID
     *
     * Generated from protobuf field <code>string PlayAuthId = 22;</code>
     */
    protected $PlayAuthId = '';
    /**
     *水印类型
     *
     * Generated from protobuf field <code>string LogoType = 23;</code>
     */
    protected $LogoType = '';
    /**
     *音频质量
     *
     * Generated from protobuf field <code>string Quality = 24;</code>
     */
    protected $Quality = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $FileId
     *          文件ID
     *     @type string $Md5
     *           hash值
     *     @type string $FileType
     *           文件类型 video/audio
     *     @type string $Format
     *          视频格式
     *     @type string $Codec
     *          编码类型
     *     @type string $Definition
     *          视频分辨率
     *     @type string $MainPlayUrl
     *          主播放地址
     *     @type string $BackupPlayUrl
     *          备用播放地址
     *     @type float $Bitrate
     *          码率(Kbps)
     *     @type int|string $Width
     *          视频高度
     *     @type int|string $Height
     *          视频宽度
     *     @type int|string $Size
     *          文件大小
     *     @type string $CheckInfo
     *          劫持校验信息
     *     @type string $IndexRange
     *           dash segment_base 分片信息
     *     @type string $InitRange
     *           dash segment_base 分片信息
     *     @type int|string $PreloadSize
     *          预加载大小
     *     @type int|string $PreloadMinStep
     *          最小步长
     *     @type int|string $PreloadMaxStep
     *          最大步长
     *     @type int|string $PreloadInterval
     *          间隔,提前加载时长
     *     @type string $P2pVerifyUrl
     *           p2p点播时，校验文件地址
     *     @type string $PlayAuth
     *          加密过的秘钥
     *     @type string $PlayAuthId
     *          密钥keyID
     *     @type string $LogoType
     *          水印类型
     *     @type string $Quality
     *          音频质量
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Models\GPBMetadata\VodCommon::initOnce();
        parent::__construct($data);
    }

    /**
     *文件ID
     *
     * Generated from protobuf field <code>string FileId = 1;</code>
     * @return string
     */
    public function getFileId()
    {
        return $this->FileId;
    }

    /**
     *文件ID
     *
     * Generated from protobuf field <code>string FileId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFileId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FileId = $var;

        return $this;
    }

    /**
     * hash值
     *
     * Generated from protobuf field <code>string Md5 = 2;</code>
     * @return string
     */
    public function getMd5()
    {
        return $this->Md5;
    }

    /**
     * hash值
     *
     * Generated from protobuf field <code>string Md5 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMd5($var)
    {
        GPBUtil::checkString($var, True);
        $this->Md5 = $var;

        return $this;
    }

    /**
     * 文件类型 video/audio
     *
     * Generated from protobuf field <code>string FileType = 3;</code>
     * @return string
     */
    public function getFileType()
    {
        return $this->FileType;
    }

    /**
     * 文件类型 video/audio
     *
     * Generated from protobuf field <code>string FileType = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFileType($var)
    {
        GPBUtil::checkString($var, True);
        $this->FileType = $var;

        return $this;
    }

    /**
     *视频格式
     *
     * Generated from protobuf field <code>string Format = 4;</code>
     * @return string
     */
    public function getFormat()
    {
        return $this->Format;
    }

    /**
     *视频格式
     *
     * Generated from protobuf field <code>string Format = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->Format = $var;

        return $this;
    }

    /**
     *编码类型
     *
     * Generated from protobuf field <code>string Codec = 5;</code>
     * @return string
     */
    public function getCodec()
    {
        return $this->Codec;
    }

    /**
     *编码类型
     *
     * Generated from protobuf field <code>string Codec = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCodec($var)
    {
        GPBUtil::checkString($var, True);
        $this->Codec = $var;

        return $this;
    }

    /**
     *视频分辨率
     *
     * Generated from protobuf field <code>string Definition = 6;</code>
     * @return string
     */
    public function getDefinition()
    {
        return $this->Definition;
    }

    /**
     *视频分辨率
     *
     * Generated from protobuf field <code>string Definition = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDefinition($var)
    {
        GPBUtil::checkString($var, True);
        $this->Definition = $var;

        return $this;
    }

    /**
     *主播放地址
     *
     * Generated from protobuf field <code>string MainPlayUrl = 7;</code>
     * @return string
     */
    public function getMainPlayUrl()
    {
        return $this->MainPlayUrl;
    }

    /**
     *主播放地址
     *
     * Generated from protobuf field <code>string MainPlayUrl = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setMainPlayUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->MainPlayUrl = $var;

        return $this;
    }

    /**
     *备用播放地址
     *
     * Generated from protobuf field <code>string BackupPlayUrl = 8;</code>
     * @return string
     */
    public function getBackupPlayUrl()
    {
        return $this->BackupPlayUrl;
    }

    /**
     *备用播放地址
     *
     * Generated from protobuf field <code>string BackupPlayUrl = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setBackupPlayUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->BackupPlayUrl = $var;

        return $this;
    }

    /**
     *码率(Kbps)
     *
     * Generated from protobuf field <code>float Bitrate = 9;</code>
     * @return float
     */
    public function getBitrate()
    {
        return $this->Bitrate;
    }

    /**
     *码率(Kbps)
     *
     * Generated from protobuf field <code>float Bitrate = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setBitrate($var)
    {
        GPBUtil::checkFloat($var);
        $this->Bitrate = $var;

        return $this;
    }

    /**
     *视频高度
     *
     * Generated from protobuf field <code>int64 Width = 10;</code>
     * @return int|string
     */
    public function getWidth()
    {
        return $this->Width;
    }

    /**
     *视频高度
     *
     * Generated from protobuf field <code>int64 Width = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkInt64($var);
        $this->Width = $var;

        return $this;
    }

    /**
     *视频宽度
     *
     * Generated from protobuf field <code>int64 Height = 11;</code>
     * @return int|string
     */
    public function getHeight()
    {
        return $this->Height;
    }

    /**
     *视频宽度
     *
     * Generated from protobuf field <code>int64 Height = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->Height = $var;

        return $this;
    }

    /**
     *文件大小
     *
     * Generated from protobuf field <code>int64 Size = 12;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->Size;
    }

    /**
     *文件大小
     *
     * Generated from protobuf field <code>int64 Size = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->Size = $var;

        return $this;
    }

    /**
     *劫持校验信息
     *
     * Generated from protobuf field <code>string CheckInfo = 13;</code>
     * @return string
     */
    public function getCheckInfo()
    {
        return $this->CheckInfo;
    }

    /**
     *劫持校验信息
     *
     * Generated from protobuf field <code>string CheckInfo = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setCheckInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->CheckInfo = $var;

        return $this;
    }

    /**
     * dash segment_base 分片信息
     *
     * Generated from protobuf field <code>string IndexRange = 14;</code>
     * @return string
     */
    public function getIndexRange()
    {
        return $this->IndexRange;
    }

    /**
     * dash segment_base 分片信息
     *
     * Generated from protobuf field <code>string IndexRange = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setIndexRange($var)
    {
        GPBUtil::checkString($var, True);
        $this->IndexRange = $var;

        return $this;
    }

    /**
     * dash segment_base 分片信息
     *
     * Generated from protobuf field <code>string InitRange = 15;</code>
     * @return string
     */
    public function getInitRange()
    {
        return $this->InitRange;
    }

    /**
     * dash segment_base 分片信息
     *
     * Generated from protobuf field <code>string InitRange = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setInitRange($var)
    {
        GPBUtil::checkString($var, True);
        $this->InitRange = $var;

        return $this;
    }

    /**
     *预加载大小
     *
     * Generated from protobuf field <code>int64 PreloadSize = 16;</code>
     * @return int|string
     */
    public function getPreloadSize()
    {
        return $this->PreloadSize;
    }

    /**
     *预加载大小
     *
     * Generated from protobuf field <code>int64 PreloadSize = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPreloadSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->PreloadSize = $var;

        return $this;
    }

    /**
     *最小步长
     *
     * Generated from protobuf field <code>int64 PreloadMinStep = 17;</code>
     * @return int|string
     */
    public function getPreloadMinStep()
    {
        return $this->PreloadMinStep;
    }

    /**
     *最小步长
     *
     * Generated from protobuf field <code>int64 PreloadMinStep = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPreloadMinStep($var)
    {
        GPBUtil::checkInt64($var);
        $this->PreloadMinStep = $var;

        return $this;
    }

    /**
     *最大步长
     *
     * Generated from protobuf field <code>int64 PreloadMaxStep = 18;</code>
     * @return int|string
     */
    public function getPreloadMaxStep()
    {
        return $this->PreloadMaxStep;
    }

    /**
     *最大步长
     *
     * Generated from protobuf field <code>int64 PreloadMaxStep = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPreloadMaxStep($var)
    {
        GPBUtil::checkInt64($var);
        $this->PreloadMaxStep = $var;

        return $this;
    }

    /**
     *间隔,提前加载时长
     *
     * Generated from protobuf field <code>int64 PreloadInterval = 19;</code>
     * @return int|string
     */
    public function getPreloadInterval()
    {
        return $this->PreloadInterval;
    }

    /**
     *间隔,提前加载时长
     *
     * Generated from protobuf field <code>int64 PreloadInterval = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPreloadInterval($var)
    {
        GPBUtil::checkInt64($var);
        $this->PreloadInterval = $var;

        return $this;
    }

    /**
     * p2p点播时，校验文件地址
     *
     * Generated from protobuf field <code>string P2pVerifyUrl = 20;</code>
     * @return string
     */
    public function getP2PVerifyUrl()
    {
        return $this->P2pVerifyUrl;
    }

    /**
     * p2p点播时，校验文件地址
     *
     * Generated from protobuf field <code>string P2pVerifyUrl = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setP2PVerifyUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->P2pVerifyUrl = $var;

        return $this;
    }

    /**
     *加密过的秘钥
     *
     * Generated from protobuf field <code>string PlayAuth = 21;</code>
     * @return string
     */
    public function getPlayAuth()
    {
        return $this->PlayAuth;
    }

    /**
     *加密过的秘钥
     *
     * Generated from protobuf field <code>string PlayAuth = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setPlayAuth($var)
    {
        GPBUtil::checkString($var, True);
        $this->PlayAuth = $var;

        return $this;
    }

    /**
     *密钥keyID
     *
     * Generated from protobuf field <code>string PlayAuthId = 22;</code>
     * @return string
     */
    public function getPlayAuthId()
    {
        return $this->PlayAuthId;
    }

    /**
     *密钥keyID
     *
     * Generated from protobuf field <code>string PlayAuthId = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setPlayAuthId($var)
    {
        GPBUtil::checkString($var, True);
        $this->PlayAuthId = $var;

        return $this;
    }

    /**
     *水印类型
     *
     * Generated from protobuf field <code>string LogoType = 23;</code>
     * @return string
     */
    public function getLogoType()
    {
        return $this->LogoType;
    }

    /**
     *水印类型
     *
     * Generated from protobuf field <code>string LogoType = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setLogoType($var)
    {
        GPBUtil::checkString($var, True);
        $this->LogoType = $var;

        return $this;
    }

    /**
     *音频质量
     *
     * Generated from protobuf field <code>string Quality = 24;</code>
     * @return string
     */
    public function getQuality()
    {
        return $this->Quality;
    }

    /**
     *音频质量
     *
     * Generated from protobuf field <code>string Quality = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setQuality($var)
    {
        GPBUtil::checkString($var, True);
        $this->Quality = $var;

        return $this;
    }

}

