<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/request/request_vod.proto

namespace Volc\Service\Vod\Models\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 点播文件域名粒度播放统计信息下载
 *
 * Generated from protobuf message <code>Volcengine.Vod.Models.Request.DescribeVodPlayFileLogByDomainRequest</code>
 */
class DescribeVodPlayFileLogByDomainRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 查询的起始时间, rfc3339格式, 最早查询1年内的数据
     *
     * Generated from protobuf field <code>string StartTime = 1;</code>
     */
    protected $StartTime = '';
    /**
     * 查询的结束时间, rfc3339；起止时间间隔不超过93天
     *
     * Generated from protobuf field <code>string EndTime = 2;</code>
     */
    protected $EndTime = '';
    /**
     * 查询域名列表, 有多个时使用英文逗号分隔
     *
     * Generated from protobuf field <code>string DomainList = 3;</code>
     */
    protected $DomainList = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $StartTime
     *           查询的起始时间, rfc3339格式, 最早查询1年内的数据
     *     @type string $EndTime
     *           查询的结束时间, rfc3339；起止时间间隔不超过93天
     *     @type string $DomainList
     *           查询域名列表, 有多个时使用英文逗号分隔
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\RequestVod::initOnce();
        parent::__construct($data);
    }

    /**
     * 查询的起始时间, rfc3339格式, 最早查询1年内的数据
     *
     * Generated from protobuf field <code>string StartTime = 1;</code>
     * @return string
     */
    public function getStartTime()
    {
        return $this->StartTime;
    }

    /**
     * 查询的起始时间, rfc3339格式, 最早查询1年内的数据
     *
     * Generated from protobuf field <code>string StartTime = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->StartTime = $var;

        return $this;
    }

    /**
     * 查询的结束时间, rfc3339；起止时间间隔不超过93天
     *
     * Generated from protobuf field <code>string EndTime = 2;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->EndTime;
    }

    /**
     * 查询的结束时间, rfc3339；起止时间间隔不超过93天
     *
     * Generated from protobuf field <code>string EndTime = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->EndTime = $var;

        return $this;
    }

    /**
     * 查询域名列表, 有多个时使用英文逗号分隔
     *
     * Generated from protobuf field <code>string DomainList = 3;</code>
     * @return string
     */
    public function getDomainList()
    {
        return $this->DomainList;
    }

    /**
     * 查询域名列表, 有多个时使用英文逗号分隔
     *
     * Generated from protobuf field <code>string DomainList = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDomainList($var)
    {
        GPBUtil::checkString($var, True);
        $this->DomainList = $var;

        return $this;
    }

}

