<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/request/request_vod.proto

namespace Volc\Service\Vod\Models\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * **********************************************************************
 * 视频剪辑云创
 * **********************************************************************
 *
 * Generated from protobuf message <code>Volcengine.Vod.Models.Request.VodAsyncVCreativeTaskRequest</code>
 */
class VodAsyncVCreativeTaskRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 产物上传空间
     *
     * Generated from protobuf field <code>string Uploader = 1;</code>
     */
    protected $Uploader = '';
    /**
     * 编辑参数
     *
     * Generated from protobuf field <code>string ParamStr = 2;</code>
     */
    protected $ParamStr = '';
    /**
     * 场景
     *
     * Generated from protobuf field <code>string Scene = 3;</code>
     */
    protected $Scene = '';
    /**
     * 回调参数
     *
     * Generated from protobuf field <code>string CallbackArgs = 4;</code>
     */
    protected $CallbackArgs = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Uploader
     *           产物上传空间
     *     @type string $ParamStr
     *           编辑参数
     *     @type string $Scene
     *           场景
     *     @type string $CallbackArgs
     *           回调参数
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\RequestVod::initOnce();
        parent::__construct($data);
    }

    /**
     * 产物上传空间
     *
     * Generated from protobuf field <code>string Uploader = 1;</code>
     * @return string
     */
    public function getUploader()
    {
        return $this->Uploader;
    }

    /**
     * 产物上传空间
     *
     * Generated from protobuf field <code>string Uploader = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUploader($var)
    {
        GPBUtil::checkString($var, True);
        $this->Uploader = $var;

        return $this;
    }

    /**
     * 编辑参数
     *
     * Generated from protobuf field <code>string ParamStr = 2;</code>
     * @return string
     */
    public function getParamStr()
    {
        return $this->ParamStr;
    }

    /**
     * 编辑参数
     *
     * Generated from protobuf field <code>string ParamStr = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParamStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParamStr = $var;

        return $this;
    }

    /**
     * 场景
     *
     * Generated from protobuf field <code>string Scene = 3;</code>
     * @return string
     */
    public function getScene()
    {
        return $this->Scene;
    }

    /**
     * 场景
     *
     * Generated from protobuf field <code>string Scene = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setScene($var)
    {
        GPBUtil::checkString($var, True);
        $this->Scene = $var;

        return $this;
    }

    /**
     * 回调参数
     *
     * Generated from protobuf field <code>string CallbackArgs = 4;</code>
     * @return string
     */
    public function getCallbackArgs()
    {
        return $this->CallbackArgs;
    }

    /**
     * 回调参数
     *
     * Generated from protobuf field <code>string CallbackArgs = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCallbackArgs($var)
    {
        GPBUtil::checkString($var, True);
        $this->CallbackArgs = $var;

        return $this;
    }

}

