<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/request/request_vod.proto

namespace Volc\Service\Vod\Models\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Request.VodCreateDramaScriptTaskRequest</code>
 */
class VodCreateDramaScriptTaskRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     */
    protected $SpaceName = '';
    /**
     * Generated from protobuf field <code>repeated string Vids = 2;</code>
     */
    private $Vids;
    /**
     * Generated from protobuf field <code>optional string ReRunDramaScriptTaskId = 3;</code>
     */
    protected $ReRunDramaScriptTaskId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $SpaceName
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Vids
     *     @type string $ReRunDramaScriptTaskId
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\RequestVod::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     * @return string
     */
    public function getSpaceName()
    {
        return $this->SpaceName;
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SpaceName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string Vids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVids()
    {
        return $this->Vids;
    }

    /**
     * Generated from protobuf field <code>repeated string Vids = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Vids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ReRunDramaScriptTaskId = 3;</code>
     * @return string
     */
    public function getReRunDramaScriptTaskId()
    {
        return isset($this->ReRunDramaScriptTaskId) ? $this->ReRunDramaScriptTaskId : '';
    }

    public function hasReRunDramaScriptTaskId()
    {
        return isset($this->ReRunDramaScriptTaskId);
    }

    public function clearReRunDramaScriptTaskId()
    {
        unset($this->ReRunDramaScriptTaskId);
    }

    /**
     * Generated from protobuf field <code>optional string ReRunDramaScriptTaskId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setReRunDramaScriptTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ReRunDramaScriptTaskId = $var;

        return $this;
    }

}

