<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/request/request_vod.proto

namespace Volc\Service\Vod\Models\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Request.VodGetMediaEntityListRequest</code>
 */
class VodGetMediaEntityListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Vid = 1;</code>
     */
    protected $Vid = '';
    /**
     * 实体类型
     *
     * Generated from protobuf field <code>string EntityTypes = 2;</code>
     */
    protected $EntityTypes = '';
    /**
     * 实体版本
     *
     * Generated from protobuf field <code>string EntityVersions = 3;</code>
     */
    protected $EntityVersions = '';
    /**
     * 来源
     *
     * Generated from protobuf field <code>string Sources = 4;</code>
     */
    protected $Sources = '';
    /**
     * 页码 
     *
     * Generated from protobuf field <code>int32 PageNumber = 5;</code>
     */
    protected $PageNumber = 0;
    /**
     * 页面大小 
     *
     * Generated from protobuf field <code>int32 PageSize = 6;</code>
     */
    protected $PageSize = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Vid
     *     @type string $EntityTypes
     *           实体类型
     *     @type string $EntityVersions
     *           实体版本
     *     @type string $Sources
     *           来源
     *     @type int $PageNumber
     *           页码 
     *     @type int $PageSize
     *           页面大小 
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\RequestVod::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Vid = 1;</code>
     * @return string
     */
    public function getVid()
    {
        return $this->Vid;
    }

    /**
     * Generated from protobuf field <code>string Vid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVid($var)
    {
        GPBUtil::checkString($var, True);
        $this->Vid = $var;

        return $this;
    }

    /**
     * 实体类型
     *
     * Generated from protobuf field <code>string EntityTypes = 2;</code>
     * @return string
     */
    public function getEntityTypes()
    {
        return $this->EntityTypes;
    }

    /**
     * 实体类型
     *
     * Generated from protobuf field <code>string EntityTypes = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityTypes($var)
    {
        GPBUtil::checkString($var, True);
        $this->EntityTypes = $var;

        return $this;
    }

    /**
     * 实体版本
     *
     * Generated from protobuf field <code>string EntityVersions = 3;</code>
     * @return string
     */
    public function getEntityVersions()
    {
        return $this->EntityVersions;
    }

    /**
     * 实体版本
     *
     * Generated from protobuf field <code>string EntityVersions = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityVersions($var)
    {
        GPBUtil::checkString($var, True);
        $this->EntityVersions = $var;

        return $this;
    }

    /**
     * 来源
     *
     * Generated from protobuf field <code>string Sources = 4;</code>
     * @return string
     */
    public function getSources()
    {
        return $this->Sources;
    }

    /**
     * 来源
     *
     * Generated from protobuf field <code>string Sources = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSources($var)
    {
        GPBUtil::checkString($var, True);
        $this->Sources = $var;

        return $this;
    }

    /**
     * 页码 
     *
     * Generated from protobuf field <code>int32 PageNumber = 5;</code>
     * @return int
     */
    public function getPageNumber()
    {
        return $this->PageNumber;
    }

    /**
     * 页码 
     *
     * Generated from protobuf field <code>int32 PageNumber = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPageNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->PageNumber = $var;

        return $this;
    }

    /**
     * 页面大小 
     *
     * Generated from protobuf field <code>int32 PageSize = 6;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->PageSize;
    }

    /**
     * 页面大小 
     *
     * Generated from protobuf field <code>int32 PageSize = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->PageSize = $var;

        return $this;
    }

}

