<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/request/request_vod.proto

namespace Volc\Service\Vod\Models\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Request.VodListBlockObjectTasksRequest</code>
 */
class VodListBlockObjectTasksRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *空间名称
     *
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     */
    protected $SpaceName = '';
    /**
     *经过urlEncode后的filename 使用,拼接 最多20个
     *
     * Generated from protobuf field <code>string FileNamesUrlEncoded = 2;</code>
     */
    protected $FileNamesUrlEncoded = '';
    /**
     *任务Id
     *
     * Generated from protobuf field <code>string TaskIds = 3;</code>
     */
    protected $TaskIds = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $SpaceName
     *          空间名称
     *     @type string $FileNamesUrlEncoded
     *          经过urlEncode后的filename 使用,拼接 最多20个
     *     @type string $TaskIds
     *          任务Id
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\RequestVod::initOnce();
        parent::__construct($data);
    }

    /**
     *空间名称
     *
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     * @return string
     */
    public function getSpaceName()
    {
        return $this->SpaceName;
    }

    /**
     *空间名称
     *
     * Generated from protobuf field <code>string SpaceName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSpaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SpaceName = $var;

        return $this;
    }

    /**
     *经过urlEncode后的filename 使用,拼接 最多20个
     *
     * Generated from protobuf field <code>string FileNamesUrlEncoded = 2;</code>
     * @return string
     */
    public function getFileNamesUrlEncoded()
    {
        return $this->FileNamesUrlEncoded;
    }

    /**
     *经过urlEncode后的filename 使用,拼接 最多20个
     *
     * Generated from protobuf field <code>string FileNamesUrlEncoded = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFileNamesUrlEncoded($var)
    {
        GPBUtil::checkString($var, True);
        $this->FileNamesUrlEncoded = $var;

        return $this;
    }

    /**
     *任务Id
     *
     * Generated from protobuf field <code>string TaskIds = 3;</code>
     * @return string
     */
    public function getTaskIds()
    {
        return $this->TaskIds;
    }

    /**
     *任务Id
     *
     * Generated from protobuf field <code>string TaskIds = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->TaskIds = $var;

        return $this;
    }

}

