<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/request/request_vod.proto

namespace Volc\Service\Vod\Models\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Request.VodSubmitDirectEditTaskSyncRequest</code>
 */
class VodSubmitDirectEditTaskSyncRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 产物上传空间
     *
     * Generated from protobuf field <code>string Uploader = 1;</code>
     */
    protected $Uploader = '';
    /**
     * Application名称
     *
     * Generated from protobuf field <code>string Application = 2;</code>
     */
    protected $Application = '';
    /**
     * 编辑参数
     *
     * Generated from protobuf field <code>bytes EditParam = 3;</code>
     */
    protected $EditParam = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Uploader
     *           产物上传空间
     *     @type string $Application
     *           Application名称
     *     @type string $EditParam
     *           编辑参数
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\RequestVod::initOnce();
        parent::__construct($data);
    }

    /**
     * 产物上传空间
     *
     * Generated from protobuf field <code>string Uploader = 1;</code>
     * @return string
     */
    public function getUploader()
    {
        return $this->Uploader;
    }

    /**
     * 产物上传空间
     *
     * Generated from protobuf field <code>string Uploader = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUploader($var)
    {
        GPBUtil::checkString($var, True);
        $this->Uploader = $var;

        return $this;
    }

    /**
     * Application名称
     *
     * Generated from protobuf field <code>string Application = 2;</code>
     * @return string
     */
    public function getApplication()
    {
        return $this->Application;
    }

    /**
     * Application名称
     *
     * Generated from protobuf field <code>string Application = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setApplication($var)
    {
        GPBUtil::checkString($var, True);
        $this->Application = $var;

        return $this;
    }

    /**
     * 编辑参数
     *
     * Generated from protobuf field <code>bytes EditParam = 3;</code>
     * @return string
     */
    public function getEditParam()
    {
        return $this->EditParam;
    }

    /**
     * 编辑参数
     *
     * Generated from protobuf field <code>bytes EditParam = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEditParam($var)
    {
        GPBUtil::checkString($var, False);
        $this->EditParam = $var;

        return $this;
    }

}

