<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/request/request_vod.proto

namespace Volc\Service\Vod\Models\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * **********************************************************************
 * 迁移平台
 * **********************************************************************
 *
 * Generated from protobuf message <code>Volcengine.Vod.Models.Request.VodSetCloudMigrateJobRequest</code>
 */
class VodSetCloudMigrateJobRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 JobId = 1;</code>
     */
    protected $JobId = 0;
    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodCloudMigrateJobSourceInfo JobSourceInfo = 2;</code>
     */
    protected $JobSourceInfo = null;
    /**
     * Generated from protobuf field <code>string CallbackAddress = 3;</code>
     */
    protected $CallbackAddress = '';
    /**
     * Generated from protobuf field <code>string SpaceName = 4;</code>
     */
    protected $SpaceName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $JobId
     *     @type \Volc\Service\Vod\Models\Business\VodCloudMigrateJobSourceInfo $JobSourceInfo
     *     @type string $CallbackAddress
     *     @type string $SpaceName
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\RequestVod::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 JobId = 1;</code>
     * @return int|string
     */
    public function getJobId()
    {
        return $this->JobId;
    }

    /**
     * Generated from protobuf field <code>int64 JobId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkInt64($var);
        $this->JobId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodCloudMigrateJobSourceInfo JobSourceInfo = 2;</code>
     * @return \Volc\Service\Vod\Models\Business\VodCloudMigrateJobSourceInfo|null
     */
    public function getJobSourceInfo()
    {
        return $this->JobSourceInfo;
    }

    public function hasJobSourceInfo()
    {
        return isset($this->JobSourceInfo);
    }

    public function clearJobSourceInfo()
    {
        unset($this->JobSourceInfo);
    }

    /**
     * Generated from protobuf field <code>.Volcengine.Vod.Models.Business.VodCloudMigrateJobSourceInfo JobSourceInfo = 2;</code>
     * @param \Volc\Service\Vod\Models\Business\VodCloudMigrateJobSourceInfo $var
     * @return $this
     */
    public function setJobSourceInfo($var)
    {
        GPBUtil::checkMessage($var, \Volc\Service\Vod\Models\Business\VodCloudMigrateJobSourceInfo::class);
        $this->JobSourceInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CallbackAddress = 3;</code>
     * @return string
     */
    public function getCallbackAddress()
    {
        return $this->CallbackAddress;
    }

    /**
     * Generated from protobuf field <code>string CallbackAddress = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCallbackAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->CallbackAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 4;</code>
     * @return string
     */
    public function getSpaceName()
    {
        return $this->SpaceName;
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSpaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SpaceName = $var;

        return $this;
    }

}

