<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/request/request_vod.proto

namespace Volc\Service\Vod\Models\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Request.VodSubmitCloudMigrateJobRequest</code>
 */
class VodSubmitCloudMigrateJobRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 JobId = 1;</code>
     */
    protected $JobId = 0;
    /**
     * Generated from protobuf field <code>string SubAppId = 2;</code>
     */
    protected $SubAppId = '';
    /**
     * Generated from protobuf field <code>string SourceVid = 3;</code>
     */
    protected $SourceVid = '';
    /**
     * Generated from protobuf field <code>string TargetVid = 4;</code>
     */
    protected $TargetVid = '';
    /**
     * Generated from protobuf field <code>string CallbackArgs = 5;</code>
     */
    protected $CallbackArgs = '';
    /**
     * Generated from protobuf field <code>string SpaceName = 6;</code>
     */
    protected $SpaceName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $JobId
     *     @type string $SubAppId
     *     @type string $SourceVid
     *     @type string $TargetVid
     *     @type string $CallbackArgs
     *     @type string $SpaceName
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\RequestVod::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 JobId = 1;</code>
     * @return int|string
     */
    public function getJobId()
    {
        return $this->JobId;
    }

    /**
     * Generated from protobuf field <code>int64 JobId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setJobId($var)
    {
        GPBUtil::checkInt64($var);
        $this->JobId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SubAppId = 2;</code>
     * @return string
     */
    public function getSubAppId()
    {
        return $this->SubAppId;
    }

    /**
     * Generated from protobuf field <code>string SubAppId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->SubAppId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SourceVid = 3;</code>
     * @return string
     */
    public function getSourceVid()
    {
        return $this->SourceVid;
    }

    /**
     * Generated from protobuf field <code>string SourceVid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceVid($var)
    {
        GPBUtil::checkString($var, True);
        $this->SourceVid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TargetVid = 4;</code>
     * @return string
     */
    public function getTargetVid()
    {
        return $this->TargetVid;
    }

    /**
     * Generated from protobuf field <code>string TargetVid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetVid($var)
    {
        GPBUtil::checkString($var, True);
        $this->TargetVid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CallbackArgs = 5;</code>
     * @return string
     */
    public function getCallbackArgs()
    {
        return $this->CallbackArgs;
    }

    /**
     * Generated from protobuf field <code>string CallbackArgs = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCallbackArgs($var)
    {
        GPBUtil::checkString($var, True);
        $this->CallbackArgs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 6;</code>
     * @return string
     */
    public function getSpaceName()
    {
        return $this->SpaceName;
    }

    /**
     * Generated from protobuf field <code>string SpaceName = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSpaceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SpaceName = $var;

        return $this;
    }

}

