<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/request/request_vod.proto

namespace Volc\Service\Vod\Models\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Volcengine.Vod.Models.Request.VodUpdateWorkflowTemplateRequest</code>
 */
class VodUpdateWorkflowTemplateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 模板ID 
     *
     * Generated from protobuf field <code>string TemplateId = 1;</code>
     */
    protected $TemplateId = '';
    /**
     * 模板名称 
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    protected $Name = '';
    /**
     * 模板描述 
     *
     * Generated from protobuf field <code>string Description = 3;</code>
     */
    protected $Description = '';
    /**
     * 任务列表 
     *
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.Activity Activities = 7;</code>
     */
    private $Activities;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $TemplateId
     *           模板ID 
     *     @type string $Name
     *           模板名称 
     *     @type string $Description
     *           模板描述 
     *     @type \Volc\Service\Vod\Models\Business\Activity[]|\Google\Protobuf\Internal\RepeatedField $Activities
     *           任务列表 
     * }
     */
    public function __construct($data = NULL) {
        \Volc\Service\Vod\Models\GPBMetadata\RequestVod::initOnce();
        parent::__construct($data);
    }

    /**
     * 模板ID 
     *
     * Generated from protobuf field <code>string TemplateId = 1;</code>
     * @return string
     */
    public function getTemplateId()
    {
        return $this->TemplateId;
    }

    /**
     * 模板ID 
     *
     * Generated from protobuf field <code>string TemplateId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTemplateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->TemplateId = $var;

        return $this;
    }

    /**
     * 模板名称 
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * 模板名称 
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * 模板描述 
     *
     * Generated from protobuf field <code>string Description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->Description;
    }

    /**
     * 模板描述 
     *
     * Generated from protobuf field <code>string Description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->Description = $var;

        return $this;
    }

    /**
     * 任务列表 
     *
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.Activity Activities = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActivities()
    {
        return $this->Activities;
    }

    /**
     * 任务列表 
     *
     * Generated from protobuf field <code>repeated .Volcengine.Vod.Models.Business.Activity Activities = 7;</code>
     * @param \Volc\Service\Vod\Models\Business\Activity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActivities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Volc\Service\Vod\Models\Business\Activity::class);
        $this->Activities = $arr;

        return $this;
    }

}

